### ISSUE TITLE
National Statistics

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#1]
Key national statistics such as demographic and economic indicators (GDP, unemployment, population, etc). To satisfy this category, the following minimum criteria must be met:

GDP for the whole country updated at least quarterly
Unemployment statistics updated at least monthly
Population updated at least once a year

http://index.okfn.org/dataset/statistics/

**Comment by boamaod** [comment]
Why was this issue closed?

**Comment by andreskytt** [comment]
Because the dataset is available to my knowledge at the board of statistics. Please comment with specifics if something is missing

**Comment by andreskytt** [comment]
http://pub.stat.ee/px-web.2001/dialog/statfile2.asp is the current statistics database. Will enquiry about the new one.

**Comment by infokujur** [comment]
Discussion about searching national statistics through opendata.riik.ee will be updated here: https://github.com/okestonia/jkan/issues/113
