### ISSUE TITLE
Visualizing SDG16 - data missing

### ISSUE THREAD

**Issue by kaiklandorf** [okestonia/opendata-issue-tracker#101]
Korruptsiooni tajumise indeks
Määratlemata kodakondsusega isikute arv
Elanike osakaal, kes hindab oma lähipiirkonda turvaliseks
Vägivaldse ründe tagajärjel hukkunute arv
Aasta jooksul vägivalla ohvriks langenud elanikud

**Comment by kaiklandorf** [comment]
Korruptsiooni tajumise indeks - leitav http://www.transparency.ee/cm/uudised/eesti-seisab-korruptsioonitajumise-indeksis-paigal

**Comment by alarirammo** [comment]
Aasta jooksul vägivalla ohvriks langenud elanikud – http://www.kriminaalpoliitika.ee/et/uuringud-ja-analuusid/ohvriuuring

**Comment by alarirammo** [comment]
Vägivaldse ründe tagajärjel hukkunute arv –  http://pxweb.tai.ee/PXWeb2015/pxweb/et/01Rahvastik/01Rahvastik__04Surmad/SD21.px/?rxid=f02879f4-1a1e-4a7b-abeb-d9fa57ca3dd0

**Comment by infokujur** [comment]
@keeganmcbride Please take data from this thread and add to opendata.riik.ee

**Comment by infokujur** [comment]
- Indeks arvutatud ja alusandmed siin: https://www.stat.ee/stat-saastva-arengu-naitajad-16
Andmebaasis siin: http://andmebaas.stat.ee/Index.aspx?lang=et&DataSetCode=SN10

- Searching Statistics Estonia will be taken care here: https://github.com/okestonia/jkan/issues/113

- Discussion about how we will handle data about Estonia will be discussed here: 
https://github.com/okestonia/jkan/issues/148
