### ISSUE TITLE
SDG 1

### ISSUE THREAD

**Issue by Heidi5000** [okestonia/opendata-issue-tracker#104]
Absoluutse vaesuse määr
Suhtelise vaesuse määr
Kodumajapidamiste säästumäär
Suhtelisesvaesuses või sotsiaalses tõrjutuses  elavate inimeste osakaal

**Comment by infokujur** [comment]
I'm closing this epic for now.
Please do open also any requests separately or if You have data, then please upload it to opendata.riik.ee

Searching Statistics Estonia will be continued here:
https://github.com/okestonia/jkan/issues/113
