### ISSUE TITLE
Avalehe jaluses vahetada välja tekst

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#109]
Avalehe all vahetada: „Avaandmete portaal valmib EL struktuurifondide programmist „Infoühiskonna teadlikkuse tõstmine“ Euroopa Regionaalarengu Fondi rahastusel.“ 
Teksti vastu: "Avaandmete portaali sisustatakse Euroopa Liidu struktuuritoetuse toetusskeemist "Infoühiskonna teadlikkuse tõstmine", mida rahastab Euroopa Regionaalarengu Fond".

**Comment by keeganmcbride** [comment]
Looking into it.

**Comment by keeganmcbride** [comment]
Fixed, the footer had been hardcoded for some reason. I changed the footer in page.tpl.php and page--front.tpl.php back so that it was implemented correctly as a block.
