### ISSUE TITLE
Add tekst on /about page

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#110]
https://opendata.riik.ee/et/about

**Mis on avaandmete portaal**
_To add this text >_
Avaandmete portaal on valminud 2015 aastal EL struktuurifondide programmist „Infoühiskonna teadlikkuse tõstmine“ Euroopa Regionaalarengu Fondi rahastusel. Projekti „Avaandmete valdkonna edendamine“ (veebruar 2018 – jaanuar 2021) käigus uuendatakse avaandmete portaali sisu. Projekti tegevused viib läbi MTÜ Open Knowledge Estonia.

**Comment by keeganmcbride** [comment]
Tehtud.
