### ISSUE TITLE
Estonian explanations for issue tracker

### ISSUE THREAD

**Issue by boamaod** [okestonia/opendata-issue-tracker#111]
I think we should have basic information on issue tracker and its goals also in Estonian. Although most of people are fine with English, having short explanation and committing guidelines in Estonian would be welcoming for at least some of us. I am mainly suggesting to have this kind of language parallelism for opening page here:

* https://github.com/okestonia/opendata-issue-tracker

Probably we should also explicitly welcome filing issues in Estonian, if needed.

**Comment by infokujur** [comment]
Siin on eesti keeles ka olemas, täiendasin pealkirja:
https://github.com/okestonia/opendata-issue-tracker/blob/master/KAAST%C3%96%C3%96_CONTRIBUTING.md

ReadME kohta on teema olemas siin: https://github.com/okestonia/opendata-issue-tracker/issues/116
