### ISSUE TITLE
opendata.riik.ee statistika

### ISSUE THREAD

**Issue by jtali** [okestonia/opendata-issue-tracker#113]
Tere

Statistika ei toimi : https://opendata.riik.ee/en/data/site-usage/dataset?month=All+months&publisher=maaeluministeerium

**Comment by keeganmcbride** [comment]
This is a known issue, there is some issues with how stats are gathered on publishers (note that: https://opendata.riik.ee/en/data/site-usage/publisher 500s), but fixes are coming.

**Comment by infokujur** [comment]
opendata.riik.ee has data feeds done: https://github.com/okestonia/jkan/issues/60
Siia peale oleks vaja ehitada dashboard, aga sellel ei ole veel konkreetset lähteülesannet.
Meil on vaja kirjeldada rahvusvaheliste raportite jaoks avaandmete seisu. See info on mõistlik panna. Kui me jõuame sellega konkreetsemaks, siis kirjeldame portaali repos ära.

Aga julgustan ka omalt poolt _issue_ avamist, kui mingit liiki statistikaga on kiirem ja seda feedide kaudu kätte ei saa.
