### ISSUE TITLE
X-tee teenuste kirjeldused

### ISSUE THREAD

**Issue by vladsrynty** [okestonia/opendata-issue-tracker#115]
Probleem riigi andmebaaside x-tee teenuste kirjeldustega. 
Vanas RIHAS - https://vana.riha.ee/riha/main olid kõikide teenuste kirjeldused ja wsdl-id olemas 
Uuel lehel https://www.riha.ee/ neid enam ei ole.

Kas riik on teenuste kirjelduse kaotamas?

**Comment by tormi** [comment]
Ehk on see viide abiks: https://abi.riha.ee/APIabi#kuidas-andmeid-p%C3%A4rida

**Comment by tormi** [comment]
Tundub, et sealtkaudu siiski WSDL-ide aadresse ei leia, sry..

**Comment by andreskytt** [comment]
See on RIA teema. Uues RIHAs peaks disaini järgi kõik asjad masinloetaval kujul olemas olema. Aga ei ole. Ehk, ei ole mingit põhjust, miks nad seal ei võiks välja paista.

**Comment by ToomasMolder** [comment]
Täpsustan, et riigil ei ole "andmebaase". 
Riigi infosüsteemi halduse infosüsteemis (RIHA) registreeritakse kõik andmekogud ja riigi infosüsteemi kuuluvad andmekoguga seotud infosüsteemid. Riigi infosüsteemi kuulub RIHA-s registreeritud andmekogu, mis on liidestatud infosüsteemide andmevahetuskihiga (edaspidi X-tee).

X-tee teenuste kirjeldused asuvad WSDL failides, mis omakorda asuvad asutuse turvaserveris, mis vastavat teenust pakub.

Selleks, et need teenuste kirjeldused (WSDL) oleks paremini ja laiemalt kättesaadavad ka nendele arendajatele, kes ise ei ole X-tee liikmed, on RIA need koondanud nn X-tee kataloogi. 
NB! Tegu on eksperimentaalse lahendusega, mille aadress, kättesaadavus ja formaat võib muutuda:
* ee-dev https://www.x-tee.ee/catalogue/ee-dev/wsdls/
* ee-test https://www.x-tee.ee/catalogue/ee-test/wsdls/
* EE https://www.x-tee.ee/catalogue/EE/wsdls/

**Comment by tormi** [comment]
Aitäh, @ToomasMolder !

Eeldaks siiski, et https://www.x-tee.ee/catalogue/ ja https://www.riha.ee/Infos%C3%BCsteemid?sort=meta.update_timestamp&dir=DESC oleks integreeritud. Riik ise on kehtestanud põhiandmete kasutamise põhimõte, eat your own dog foot, please :)

**Comment by ToomasMolder** [comment]
RIHA kohta - https://github.com/okestonia/jkan/pull/190/commits/99b88a0cb92bc010f837ded7924037ee22f79328
X-tee teenuste kataloogi kohta - 
https://github.com/okestonia/jkan/pull/191/commits/6f063f2c1ef9c495d6399c3128b7114f61bb0283

NB! 2019/02/13 seisuga on X-tee kataloog ajutine ja mittetäiuslik / poolik lahendus. RIA-l on projekti "X-tee teenusega liitumise ja liikmelisuse haldamise lihtsustamine" koosseisus loomisel keskkond, mille arenduse käigus on soov seda kataloogi täiendada funktsionaalsustega. Samuti on koostöös MKMi veetava arhitektuurinõukoguga algamas RIHA tuleviku kontseptsiooni visiooni uuendamine ja seal saab muuhulgas selgeks antud kataloogi võimalik paiknemine ja seos RIHA-ga.

@tormi  - Eeldamine on kõikide ebaõnnestumiste vaimne ema.
Sõnakasutus "eat your own dog foot, please" ei kuulu täitmisele isegi juhul kui see on markeeritud naerunäoga :)

**Comment by tormi** [comment]
Ok, siirad vabandused ja tänud info eest!
