### ISSUE TITLE
Buildings data - accessibility, energy efficiency, etc.

### ISSUE THREAD

**Issue by maarjatoots** [okestonia/opendata-issue-tracker#126]
Splitting #15 into two issues. The second part concerns building information:

"For the buildings layer, information there would have data about accessibility, energy efficiency, safety, overall price levels etc."

**Comment by infokujur** [comment]
I assume this is a question for Ehitisregister?

**Comment by Kristjan4** [comment]
Ehitisregister is collecting partially accessibility and energy efficency data (lift information, builiding energy labels). This information is already available https://opendata.riik.ee/andmehulgad/ehitisregister/
