### ISSUE TITLE
Company Register - Open Data Index

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#13]
List of registered (limited liability) companies. The submissions in this data category does not need to include detailed financial data such as balance sheet etc. To satisfy this category, the following minimum criteria must be met:

- Name of company
- Unique identifier of the company
- Company address
- Updated at least once a month

http://global.survey.okfn.org/dataset/companies

**Comment by andreskytt** [comment]
http://avaandmed.rik.ee/andmed/ARIREGISTER/ Contains the information as CSV and XML. Contains all the requested data, last updated 2 days ago. Close, if sufficient.

**Comment by ruizcalleja** [comment]
I am surprised about this data. I think we first need to make an effort to put all the available data together in the Open Data Portal of Estonia.
This dataset is very difficult to be found and the license of the data is not clear.

**Comment by andreskytt** [comment]
True, it should be added to opendata.riik.ee. Do you mean that the license is missing or that the license is difficult to understand? AFAIK, the license is not an issue in Estonian legal context (contrary to almost everywhere else), therefore most datasets lack an explicit license.

**Comment by peepkungas** [comment]
BTW, basic organization data is also available as Register OÜ Open Data plan offering. You can request key from https://developers.ir.ee/apis/ and most of the documentation at https://developers.ir.ee/graph-api for Graph API. We also have Stream API implemented for changes. See https://developers.ir.ee/stream-api/ for Stream API documentation. All of our API's serve linked regularly updated data which you can request in XML, JSON and RDF/XML format.
