### ISSUE TITLE
Täienda - Avaandmete kataloogi siin - https://opendata.riik.ee/et/apps

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#130]

**Comment by maarjatoots** [comment]
Some possible additions (although some, e.g. Opener, don't seem to be updated any more):

Opener: http://opener.ee/ - combines data from 2013-2015 from several government databases (public procurement contracts, donations to political parties, members of political parties, members of state-owned enterprises) to visualize relationships between companies that have won public contracts and political parties, etc. 

Air quality monitoring: http://www.ohuseire.ee/ - information about air quality indicators, pollen and dispersion models on a map application

Tark tee (Smart Road): https://tarktee.mnt.ee/ - information about road conditions, restrictions and road works on a map application

Tallinna operatiivinfo: https://opinfo.tallinn.ee/kaart - map with information about road works and street closures

Tallinn Geoportal maps: https://www.tallinn.ee/est/geoportaal/Rakendused-2

Geoportal of the Estonian Land Board: http://inspire.maaamet.ee/inspire-teenused

**Comment by otuxe** [comment]
Tallinna ühistranspordi kaart: https://gis.ee/tallinn/
Eesti sadamate kaart: https://gis.ee/sadamad/
Merekaart: https://gis.ee/meri/

**Comment by infokujur** [comment]
Lisatud https://opendata.riik.ee/rakendused/
