### ISSUE TITLE
Täienda - Avaandmete üritused Läänemere ääres - (open)data events in our region

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#131]
If You know something happening, please post info into this thread.

**Comment by IngridJa** [comment]
Open Data Hackathon in Riga September 28-29: https://lata.org.lv/hackathon/. FB event: https://www.facebook.com/events/1341885852608631/.

**Comment by infokujur** [comment]
Sama nagu siin: https://github.com/okestonia/opendata-issue-tracker/issues/88

Infochannels for the future:
Blog: https://opendata.riik.ee/blogi/
FB group: https://www.facebook.com/groups/1792458637715167/
Twitter: https://twitter.com/openESTdata (not yet in use)

Post there and use tag #openESTdata
