### ISSUE TITLE
Datasets shared by PPA at open data portal are no longer accessible 

### ISSUE THREAD

**Issue by IngridJa** [okestonia/opendata-issue-tracker#132]
Page not found for several PPA datasets shared at opendata.riik.ee, for example: Eesti Vabariigi piiripunktid, PPA politseijaoskondade kontaktid, PPA kontaktid.

**Comment by infokujur** [comment]
https://opendata.riik.ee/andmehulgad/?organization=politsei-ja-piirivalveamet-ppa

PPA is renewing its open data.
