### ISSUE TITLE
Rahandusministeeriumi ülevaade avaandmetest ja plaanidest

### ISSUE THREAD

**Issue by Reelikavahopski** [okestonia/opendata-issue-tracker#136]
Rahandusministeerium on avaldanud Avaandmete portaalis https://opendata.riik.ee/ järgmised avaandmed:
•	Euroopa Liidu Struktuuritoetus
•	Riigihangete register
•	Riigi kinnisvararegister
Samuti on olemas riigiraha rakendus http://riigiraha.fin.ee

Planeerimisel on Riigihangete registri arendus, mille üheks tegevuseks on parandada avaandmete kättesaadavuse taset.

Reelika Vahopski
reelika.vahopski@fin.ee
Teadusnõunik
Rahandusministeerium

**Comment by infokujur** [comment]
On viidatud siin: https://opendata.riik.ee/publishers/rahandusministeerium/
Küsimused andmehulkade kohta on siin: https://github.com/okestonia/opendata-issue-tracker/labels/RAM
