### ISSUE TITLE
EHRi avaandmed ei ole mõistlikul kujul

### ISSUE THREAD

**Issue by andreskytt** [okestonia/opendata-issue-tracker#138]
EHRi avaandmestik on saadaval ainult sellisel kujul, nagu kirjeldatud siin: https://avaandmed.ehr.ee/avaandmed_abi.pdf . Protsess on täielikult asünkroonne (saab esitada tellimuse, selle täitmisest teavitatakse e-postiga) ja katistud parooliga. 

Peaks olema mõistlikult ligipääsetav API või kindlate perioodide (igakuised, aastased vms.) andmefailid alla laadimiseks.

**Comment by infokujur** [comment]
More about Ehitisregister here: https://github.com/okestonia/opendata-issue-tracker/issues/41

**Comment by Kristjan4** [comment]
EHR avaandmed on realiseeritud asünkroonselt, kuna tegemist on mahukate andmefailidega, mida pole tehniliselt otstarbekas realiseerida sünkroonsena. Avaandmed on realiseeritud vastavuses rohelise raamatuga, ehk:
1.	Kindlate perioodide järel koostatav andmefail alla laadimiseks. Kasutaja valib EHR avaandmete kodulehel soovitud avaandmete faili ning talle edastatakse link millelt saab faili alla laadida. Link pole parooliga kaitstud.
2.	API, mis võimaldab EHR avaandmeid laadida masinkujul. API kirjeldus on toodud EHR kodulehel:
Aruande tellimine
Aruande tellimiseks tehakse POST päring:
POST https://<server>/api/v1/reports
Päringu sisuks on tellitava aruande parameetrid:
•	aruande nimetus
•	aasta
•	kuu
•	e-posti aadress, millele saadetakse teavitus aruande valmimisest ning link selle alla laadimiseks
Näiteks:
{
"report_code": "EHITISED",
"email_address": "marju.kask@gmail.com",
"year": 2017,
"month": 6
}

**Comment by timotoots** [comment]
Arusaadav, et failid on suured. Aga sel juhul võiks e-postiga teavitus toimuda juhul kui reaalselt küsitakse suuri faile. Kui tahta luua süsteemi, mis automaatselt igapäevaselt end uuendustega kursis hoiab, on praegune variant ebavajalikult keeruline. Uuenduste suurused on väiksed ja võiksid vabalt sünkroonis töötada. Masinloetava API üks idee on see, et seda saavad masinad otse "tarbida". E-posti teavitus ei ole selleks parim lahendus.

**Comment by tormi** [comment]
> Avaandmed on realiseeritud vastavuses rohelise raamatuga

Võib-olla tuleks siis algatada viidatud rohelise raamatu muutmine.

Paluks EHR avaandmeid kas http://spec.graphql.org/, https://jsonapi.org/format/ või muud üldlevinud API spetsifikatsiooni kasutades. Hetkel realiseeritud aruannete väljundit EHR Avaandmete API'ks nimetada on liiga pidulik, see ei ole rakendustes mõistlikult kasutatav.

**Comment by Kristjan4** [comment]
Arusaadav, et praegu tehtud lahendus ei ole kõige sobilikum. Seoses uue e-ehituse platvormi arendamisega oleme oluliselt muutmas Ehitisregistri arhitektuuri. Uute API teenuste kirjeldused hakkavad tekkima aadressil : https://swaggerui.ehr.ee/ . Planeerime sügisel tulla välja 2 avaliku API teenusega : aadressi peale EHR koodi väljastamine, EHR koodi alusel ehitise detailandmete väljastamine. Eelkõige on nende teenuste vajadused tekkinud kinnisvara sektori ootustest, kes soovivad enda süsteemides EHR-i andmeid kasutada.
Mõistlik saada siit tagasisidet, milliseid teenuseid ollakse ootamas EHR-i poolt, siis saaksime nendega arvestada arenduste läbiviimisel ja prioriteetide seadmisel.

**Comment by tormi** [comment]
Super, aitäh!

**Comment by wipsise** [comment]
Huvitaks kuidas API kaudu projekti mudelit EHRi üles laadida?
