### ISSUE TITLE
Crime, danger, violence

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/opendata-issue-tracker#14]
Idea from Tartu hackathon: 
Coordinates and specifics of crime This would predict future location or future crimes and visualize current crime levels.

**Comment by andreskytt** [comment]
PPA folks are working on it, expecting results soonish

**Comment by infokujur** [comment]
https://opendata.riik.ee/et/dataset/avaliku-korra-vastased-ja-avalikus-kohas-toime-pandud-syyteod

All here!
