### ISSUE TITLE
KPOIS tehnovõrgu omaniku väljavõte

### ISSUE THREAD

**Issue by tormi** [okestonia/opendata-issue-tracker#147]
Aadressilt https://geoportaal.maaamet.ee/est/Teenused/Talumistasu-kalkulaator-p635.html saab KPOIS andmebaasist teha csv-formaadis kitsenduste andmete väljavõtteid tehnovõrgu omanike lõikes. Väljavõttele lisatud readme:

Tegemist on kitsenduste rakenduse (KPOIS) väljavõttega. Tabeleid uuendatakse käesoleva aasta kohta 31. kuupäeva seisuga igakuiselt. Eelneva aasta seis, mille alusel omanikul on õigus küsida talumistasu on 31.12 kuupäeva seisuga.

Tabelis on esitajate lõikes välja toodud katastriüksused koos talumistasu suurusega.

## Veergude seletused

- KY_TUNNUS - kitsendusega koormatud katastriüksuse tunnus
- PINDALA - katastriüksuse registreeritud pindala (m²) katastris
- SIHT1 kuni SIHT3 - katastriüksuse sihtotstarve
- SO_PRTS1 kuni SO_PRTS3 - katastriüksuse sihtotstarbe ulatus protsentides (%)
- MAKSHINDKOKKU - katastriüksuse maksustamishind
- KTS_PIND - katastriüksuse kitsenduse ulatus (m²)
- TT - talumistasu maksimaalne suurus eurodes
- KTS_PIND_+90% - märkus "jah", kui kitsenduse ulatus on üle 90% maaüksuse pindala.
- VALEM - talumistasu arvutuse valem
- NAHTUS - kitsendust põhjustav objekti üldine nimetus
- VOOND - kitsendust põhjustava objekti vööndi nimetus
- VALJAVOTE - csv väljavõtte kuupäev

![talumistasu kalkulaator geoportaal maa amet](https://user-images.githubusercontent.com/146800/49426883-8c96e380-f7aa-11e8-876d-3ba50838c7fc.png)

**Comment by infokujur** [comment]
Infot uuendada siin: https://opendata.riik.ee/andmehulgad/?organization=maa-amet

**Comment by otuxe** [comment]
ma ei leia siit
 probleemi püstitusest küsimust, kuid isikut, kes esitab tehnovõrgu
kohta andmed kitsenduste infosüsteemi, saab küsida Kitsenduste
kaardirakendusest (kasutades&nbsp; kaardiaknas infopäringut ja klikkides
objekti peal). Kuna Maa-amet ei saa õiguslikult avaandmetena jagada
kolmandate isikute andmeid (tehnovõrgu objektide ruumikujusid), siis ei
ole praegu teist moodust kui huvi korral infot näiteks trassi kohta
kaardirakenduse kaudu ükshaaval küsida/vaadata.
