### ISSUE TITLE
City planning/city data

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/opendata-issue-tracker#15]
Idea from Tartu hackathon:
 First two ideas for layers were parks and buildings. Using mobile positioning services, it can be determined which parks are actively in use and should be kept as parks and which ones are underused and therefore could either be used for buildings or repurposed, redeveloped. For the buildings layer, information there would have data about accessibility, energy efficiency, safety, overall price levels etc.

**Comment by andreskytt** [comment]
Do you mean this for the entire country, cities only, or would be Tallinn, Tartu, Pärnu, Narva be sufficient?

**Comment by TELLAKVERE** [comment]
It would be nice to compare with other cities. Estonia vs Finland. So we need Fedaration of  Cities Mayors Who Believe in Open Data (FCMWBOD)

**Comment by boamaod** [comment]
I understand that there is national register of buildings (as in #41) and then about usage and other parameters of the buildings each owner of building (be it state, municipality or private owner) keeps track on its own, is that so? For example state real estate register (as in #21) keeps track on status of buildings owned by the state?

By the way, what exactly is this issue about? Publishing mobile usage data or data about buildings or city planning data? This issue might need separating into more than one issues.

**Comment by tormi** [comment]
Tallinn's planning opendata: http://www.tallinn.ee/est/ehitus/Masinliides

**Comment by tormi** [comment]
There is also 2 country-wide plannings registries without opendata capabilities:
* https://rpis.andmevara.ee/ and
* http://xgis.maaamet.ee/xGIS/XGis?app_id=MA15A&user_id=at&bbox=324653.846153846,6375000,780346.153846154,6635000&LANG=1

**Comment by tormi** [comment]
Saue: http://www.tarkvarastuudio.ee/saue/?menu_id=plan&nmapwidth=1

**Comment by tormi** [comment]
I know that [MoF's Spatial Planning Department](http://www.fin.ee/kontaktid#plo) is evaluating the concept of new countrywide planning register.

**Comment by tormi** [comment]
https://sauevald.github.io/yldplaneering/#11/59.2768/24.4703/osm-sauevyp-sauelyp-kernuyp-nissiyp

**Comment by maarjatoots** [comment]
Split into two more manageable chunks: #124 and #126
@infokujur, please close
