### ISSUE TITLE
Lipupäevad

### ISSUE THREAD

**Issue by reijosirila** [okestonia/opendata-issue-tracker#150]
Sooviks avaandmetena näha lipupäevasi, mida kasutab nt. eesti.ee

**Comment by andreskytt** [comment]
Kas https://opendata.riik.ee/andmehulgad/lipupaevad/ sobib?

**Comment by reijosirila** [comment]
Sobib, kui sinna valimisepäevad, rahvahääletuse jms päevad tekivad? Ja ujuvad päeva ka muutuma hakkavad?
