### ISSUE TITLE
Eesti Rahva Muuseumi fotoarhiiv ja vaibakogu 

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#164]
Eesti Rahva Muuseumi fotoarhiivi ja vaibakogu tuleks teha avaandmetena kättesaadavaks.
@kaittik

**Comment by fredansip** [comment]
ERMi poolt on kantud MUISi nii digitaalsed kujutised, kui ka metainfo ja see on kätte saadav MUIS opendata liidese http://opendata.muis.ee/ kaudu.

**Comment by infokujur** [comment]
https://opendata.riik.ee/andmehulgad/muuseumide-infos-steemi-avaandmed/ Siia viidatud, kuid 2015 seisuga?

**Comment by otuxe** [comment]
Liidese info on sama. Mis seal valesti on?
