### ISSUE TITLE
Eesti treenerite ja spordiorganisatsioonide (spordiklubid, spordikoolid, alaliidud, maakondlikud liidud, spordiühendused) register 

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#168]
Eesti treenerite ja spordiorganisatsioonide (spordiklubid, spordikoolid, alaliidud, maakondlikud liidud, spordiühendused) registri andmed peaksid olema avaandmetena kättesaadavad.

**Comment by timotoots** [comment]
https://www.spordiregister.ee/opendata/ Siin nagu midagi on.
