### ISSUE TITLE
Water Quality - Open Data Index

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#17]
Data, measured at the water source, on the quality of water is essential for both the delivery of services and the prevention of diseases. In order to satisfy the minimum requirements for this category, data should be available on level of the following chemicals by water source.

- Fecal coliform
- Arsenic
- Fluoride levels
- Nitrates
- Total Dissolved Solids
- Data per water source
- Available for entire country

http://global.survey.okfn.org/dataset/water

**Comment by andreskytt** [comment]
Large amounts of data available via https://opendata.riik.ee/en/dataset/vee-terviseohutuse-infos-steemi-avalikud-andmed. Close if sufficient

**Comment by infokujur** [comment]
Data indeed available. Closing at the moment.
