### ISSUE TITLE
Liikluspiirangute andmestik

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#170]
Liikluspiirangute andmestik ja ka teised tarktees leiduvad andmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt avaandmete portaalis viidatud.

https://tarktee.mnt.ee/#/et/datex

**Comment by otuxe** [comment]
Maanteeametiga on käivitatud  arendusprojektid konkreetsete avaandmete tootmiseks ning praeguste plaanide järgi peaksime jõudma reaalsete tulemusteni (andmete avalikustamiseni) 2-3 kuu jooksul.

**Comment by Kristjan4** [comment]
Maanteeameti poolt on liikluspiirangute andmestik avaandmete portaalis avalikustatud : https://opendata.riik.ee/andmehulgad/maanteeamet-tarktee/
