### ISSUE TITLE
Riiklik teeregister

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#171]
[Riiklik teeregister](https://www.mnt.ee/et/tee/teeregister) peab olema kättesaadav avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by otuxe** [comment]
Maanteeametiga on käivitatud  arendusprojektid konkreetsete avaandmete tootmiseks ning praeguste plaanide järgi peaksime jõudma reaalsete tulemusteni (andmete avalikustamiseni) 2-3 kuu jooksul.

**Comment by Kristjan4** [comment]
Teeregistri avaandmed on tehtud kättesaadavaks läbi avaandmete portaali : https://opendata.riik.ee/andmehulgad/maanteeamet-teeregister/
