### ISSUE TITLE
Ehitusgeoloogia andmed

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#173]
Ehitusgeoloogia andmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by tanel2** [comment]
Ehitusegeoloogiliste uuringute andmeid näeb Maa-ameti kaardirakenduses https://xgis.maaamet.ee/xgis2/page/app/ehitusgeoloogia

**Comment by otuxe** [comment]
@tanel2 Kas oleks võimalik andmetele viidata ka avaandmete portaalis?

**Comment by tanel2** [comment]
Viide opendata.riik.ee lehele lisatud. Andmete korraga allalaadimine on realiseeritud kaardirakenduse kaudu.
