### ISSUE TITLE
Maa-ameti avaandmed pole ODP viidatud

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#174]
Palun viidata [Maa-ameti avaandmetele](https://geoportaal.maaamet.ee/est/Andmed-ja-kaardid-p1.html) avaandmete portaalis opendata.riik.ee

**Comment by tanel2** [comment]
Maa-ameti avaandmete veebileht asub aadressil https://geoportaal.maaamet.ee/avaandmed Viide opendata.riik.ee lehel on parandatud.

**Comment by otuxe** [comment]
@tanel2 Kas kõikidele Maa-ameti avaandmete portaalis viidatud andmed on ka eraldi viidatud avaandmete portaalis? Kui jah, siis sulgeks teema.

**Comment by tanel2** [comment]
Tere. Vastus jah. Teema #174 peaks sulgema, sest kõik oluline on dubleerivalt viidatud.Lisaks võiks sulgeda ka teemad #12 (haakub eelneva jutuga)#3
 (katastriandmed on avaandmed ning nendes sisaldub nii katastriüksuse 
tunnus, piiri ruumikuju kui omandivorm (eraomand, riigiomand, 
munitsipaalomand, segaomand). Maa väärtuse-hindamise teemal on siin juba
 eraldi issue #36, millele on ka justkui ühtkomateist vastatud ja ma hea
 meelega loeksin selle lahendatuks.#147 - ma ei leia siit
 probleemi püstitusest küsimust, kuid isikut, kes esitab tehnovõrgu 
kohta andmed kitsenduste infosüsteemi, saab küsida Kitsenduste 
kaardirakendusest (kasutades&nbsp; kaardiaknas infopäringut ja klikkides 
objekti peal). Kuna Maa-amet ei saa õiguslikult avaandmetena jagada 
kolmandate isikute andmeid (tehnovõrgu objektide ruumikujusid), siis ei 
ole praegu teist moodust kui huvi korral infot näiteks trassi kohta 
kaardirakenduse kaudu ükshaaval küsida/vaadata. TänanTanel Eile, 19:25 Ott Velsberg &lt;notifications@github.com&gt; Kirjutas:@tanel2 Kas kõikidele Maa-ameti avaandmete portaalis viidatud andmed on ka eraldi viidatud avaandmete portaalis? Kui jah, siis sulgeks teema.
