### ISSUE TITLE
Ravimiregistri andmed 

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#176]
Ravimiregistri andmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee.

http://ravimiregister.ravimiamet.ee/?pv=Andmed.Ravimid

**Comment by priitraspel** [comment]
Avaandmete portaali lisatud viide ravimiregistri päringule.
