### ISSUE TITLE
Tervisehoiustatistika andmed https://aveeb.sm.ee/

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#179]
[Tervisehoiustatistika andmed](https://aveeb.sm.ee/) peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by priitraspel** [comment]
Viide a-Veebile lisatud avaandmete portaali.
