### ISSUE TITLE
National Laws - Open Data Index

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#18]
This data category requires all national laws and statutes to be available online, although it is not a requirement that information on legislative behaviour e.g. voting records is available.

- Content of the law / status
- Date of last amendment
- Amendments to the law (if applicable)

http://global.survey.okfn.org/

**Comment by andreskytt** [comment]
Available at www.riigiteataja.ee. Each act has a download on their page that can be automated by simply adding ".xml" to the end. The schema is a bit fluffy and the content can be iffy (large images, portions of html etc.) but it is mostly there. Please close if sufficient.

**Comment by unserializable** [comment]
For parsing the legal XML content offered at  [www.riigiteataja.ee](www.riigiteataja.ee), there is GPLv3 licensed Java code available in [Elegadro](https://github.com/unserializable/elegadro/), handling legal acts conforming to 'tyviseadus.xml' schema. Parsing entrypoint is at `iota-parser` artifact, [SeadusParser](https://github.com/unserializable/elegadro/blob/master/iota-parser/src/main/java/org/elegadro/iota/parser/rt/xml/SeadusParser.java).
