### ISSUE TITLE
Raudteeliiklusregister

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#186]
[Raudteeliiklusregistri](https://www.tja.ee/et/valdkonnad/raudteeliiklusregister) andmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by Kristjan4** [comment]
Andmed avalikustatud https://opendata.riik.ee/andmehulgad/raudteeliiklusregister/
