### ISSUE TITLE
Maatüki kitsenduste andmed

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#188]
Maatüki kitsenduste andmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by tanel2** [comment]
Andmed on kättesaadavad aadressil https://geoportaal.maaamet.ee/avaandmed Viited opendata.riik.ee lehele on lisatud.

**Comment by otuxe** [comment]
Korras! Andmed viidatud: https://opendata.riik.ee/andmehulgad/kitsenduste-kaardi-andmed/
