### ISSUE TITLE
Tehnoülevaatustega seotud andmed

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#189]
Tehnoülevaatustega seotud andmed (tähtajad, avastatud vead, odomeetri näidud jt) peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by otuxe** [comment]
Maanteeametiga on käivitatud  arendusprojektid konkreetsete avaandmete tootmiseks ning praeguste plaanide järgi peaksime jõudma reaalsete tulemusteni (andmete avalikustamiseni) 2-3 kuu jooksul.

**Comment by Kristjan4** [comment]
Konkreetse SF projektiga seotud tehnoülevaatuste avaandmed on avalikustatud Maanteeameti poolt Eesti Avaandmete portaalis : https://opendata.riik.ee/andmehulgad/maanteeamet-liiklusregister/

**Comment by otuxe** [comment]
Teema võib sulgeda
