### ISSUE TITLE
Administrative Boundaries - Open Data Index

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#19]
Data on administrative units or areas defined for the purpose of administration by a (local) government.

- Boundary level 1
- Boundary level 2
- Coordinates (latitude, longitude)
- Name of poligone (department, region, city)
- Borders of poligone

http://global.survey.okfn.org/dataset/boundaries

**Comment by tormi** [comment]
Needs review: http://global.survey.okfn.org/submission/279d3cbc-c638-459a-ad14-5a9a13415c8e

**Comment by tormi** [comment]
I provide spatial data for Estonian Administrative and Settlement Classification in CSV, GeoJSON and TopoJSON format: https://github.com/buildig/EHAK. Monthly releases: https://github.com/buildig/EHAK/releases. 

Source data in shapefile format from Maa-amet: http://geoportaal.maaamet.ee/eng/Maps-and-Data/Administrative-and-Settlement-Division-p312.html

**Comment by andreskytt** [comment]
So the data _is_ available?

**Comment by keeganmcbride** [comment]
https://github.com/keeganmcbride/EstonianRealEstatePilot/tree/master/Linnaosa 

We have linnaosa level here, but this data shoudl be available from Maa-amet as @tormi  pointed out.

**Comment by tormi** [comment]
@andreskytt - yes, Maa-amet is providing this data in shapefile format on a monthly basis. @keeganmcbride, take a lok at the http://geoportaal.maaamet.ee/docs/haldus_asustus/asustusyksus_shp.zip for the `linnaosa` level. Preview here: https://buildig.com/EHAK/ (first map)

**Comment by tormi** [comment]
@andreskytt - MajandusKM is not the correct label, EHAK is co-maintained by the Statistical Office of Estonia and Maa-amet.
