### ISSUE TITLE
EHAK andmed, kohanimeandmed ning aadressiandmed

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#191]
EHAK andmed, kohanimeandmed ning aadressiandmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by tanel2** [comment]
Andmed on olnud aastaid kättesaadavad avaandmetena aadressil https://geoportaal.maaamet.ee/avaandmed Viited opendata.riik.ee lehele on lisatud.

**Comment by otuxe** [comment]
Korras! Viidatud: 
https://opendata.riik.ee/andmehulgad/haldus-ja-asustus-ksuste-piirid/
https://opendata.riik.ee/andmehulgad/kohanimeregister/
https://opendata.riik.ee/andmehulgad/aadressiandmed/
