### ISSUE TITLE
Sentinel  sateliidiandmed

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#192]
Sentinel  sateliidiandmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by tanel2** [comment]
Sentinel andmete puhul alustada veebilehelt https://esthub.maaamet.ee Viide opendata.riik.ee lehele lisatud.

**Comment by otuxe** [comment]
Korras! Andmed viidatud: https://opendata.riik.ee/andmehulgad/esthub-teenused/
