### ISSUE TITLE
Elektrooniline mereinfosüsteem

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#193]
Elektroonilise mereinfosüsteemi andmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by Kristjan4** [comment]
Laevakülastuse avaandmed on portaalis olemas : https://opendata.riik.ee/andmehulgad/elektrooniline-mereinfosysteem/
