### ISSUE TITLE
Tarbijate Teeninduskeskkonna Infosüsteemi

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#194]
Tarbijate Teeninduskeskkonna Infosüsteemi  andmed peaksid olema kättesaadavad avaandmetena ning nõuetekohaselt viidatud avaandmete portaalis opendata.riik.ee

**Comment by Kristjan4** [comment]
Andmed avalikustatud https://opendata.riik.ee/andmehulgad/tarbijakaitse-infosysteem/

**Comment by Kristjan4** [comment]
Oleme Tarbijate teeniduskeskkonna andmed avalikustanud : https://opendata.riik.ee/andmehulgad/tarbijakaitse-infosysteem/
