### ISSUE TITLE
Liiklusjärelevalve ja sõidukijuhi töö-, sõidu- ja puhkeaja nõuete täitmist puudutav info

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#196]
[Liiklusjärelevalve ja sõidukijuhi](https://www.mkm.ee/et/avaandmed) töö-, sõidu- ja puhkeaja nõuete täitmist puudutav info pole lisatud avaandmete portaali opendata.riik.ee

**Comment by infokujur** [comment]
Kas selle leiab kuskilt siit? https://opendata.riik.ee/andmehulgad/liiklusj-relevalve-infos-steem/

**Comment by Kristjan4** [comment]
Jah. Õige info asukoht on https://opendata.riik.ee/andmehulgad/liiklusj-relevalve-infos-steem/
