### ISSUE TITLE
Sadamate külastamisega kaasnev info

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#197]
[Sadamate külastamisega](https://www.mkm.ee/et/avaandmed) kaasnev info pole lisatud avaandmete portaali opendata.riik.ee

**Comment by Kristjan4** [comment]
Sadamate külastamise andmed ongi Elektroonilise mereinfosüsteemi andmed. Need on portaali lisatud : https://opendata.riik.ee/andmehulgad/elektrooniline-mereinfosysteem/
