### ISSUE TITLE
Raudtee rööbastee, veeremi ja raudteeohutuse alased andmed.

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#198]
[Raudtee rööbastee, veeremi ja raudteeohutuse alased andmed](https://www.mkm.ee/et/avaandmed) pole lisatud avaandmete portaali opendata.riik.ee

**Comment by Kristjan4** [comment]
Andmed avalikustatud : https://opendata.riik.ee/andmehulgad/raudteeliiklusregister/
