### ISSUE TITLE
Tarbijate pöördumiste järelevalvemenetluste jõustunud ettekirjutused ja väärteomenetluste otsused

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#199]
[Tarbijate pöördumiste järelevalvemenetluste jõustunud ettekirjutused ja väärteomenetluste otsused](https://www.mkm.ee/et/avaandmed) pole lisatud avaandmete portaali opendata.riik.ee

**Comment by Kristjan4** [comment]
Andmed avalikustatud https://opendata.riik.ee/andmehulgad/tarbijakaitse-infosysteem/

**Comment by infokujur** [comment]
Kas tulemas on andmed ka peale 01/06/2017?

**Comment by Kristjan4** [comment]
Suunasime andmepäringud otse serverisse ning uuendasime avaandmete  portaalis andmeid https://opendata.riik.ee/andmehulgad/tarbijakaitse-infosysteem/
