### ISSUE TITLE
Äriregister broken link

### ISSUE THREAD

**Issue by timotoots** [okestonia/opendata-issue-tracker#205]
in here:
https://opendata.riik.ee/andmehulgad/ariregister/

broken link:
https://avaandmed.rik.ee/andmed/ARIREGISTER/

**Comment by keeganmcbride** [comment]
@otuxe , RIK removed all the datasets from their avaandmed page and hasn't updated the metadata. I mentioned this also to @infokujur  and @andreskytt recently.

**Comment by keeganmcbride** [comment]
@otuxe @timotoots It doesn't seem to be broken anymore, has it been fixed?

**Comment by otuxe** [comment]
It is no longer broken.
