### ISSUE TITLE
Viimsi valla tulud

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#210]
Avaandmete portaalis tuleks viidata https://www.viimsidata.ee/ leitavad Viimsi valla tulude info ja lisada portaali viide ka rakenduste alla.

**Comment by keeganmcbride** [comment]
https://github.com/okestonia/jkan/commit/7bf6d7734cb766f1b7f73f3e733005aaf24017f1

**Comment by andreskytt** [comment]
@otuxe please close, if satisfactory
