### ISSUE TITLE
eesti-kirjandusmuuseumi-arhiivide-avaandmed

### ISSUE THREAD

**Issue by prksn** [okestonia/opendata-issue-tracker#211]
1. Miks võtab muudatuste tegemise tulemuste kuvamine opendata.riik.ee lehel nii kaua aega?
2. Miks e-kirjadele ei vastata? Olen saatnud kontaktideks antud e-maili aadressitele 3 kirja, aga vastuse olen saanud ühele, kuid vastusest ei selgu isegi see, millisele e-kirjale.
Asutusele on saadetud nõue, et opendata.riik.ee-le tuleb infot panna, aga samas tuge ja muudatuste sisse viimine tehakse stressirohkeks ootamiseks.

**Comment by andreskytt** [comment]
Kuna kõik asutused teevad oma muudatusi korraga, on tõepoolest paar päeva läinud enne muudatuste tegemist. Praegu peaks olema kõik muudatuste avaldamiseks valmis, eeldatavasti juhtub see ööl vastu homset.

**Comment by andreskytt** [comment]
Muutused on avalikud, sulgen teema. Kui miskit siiski ei toimi, nagu vaja, võib selle uuesti avada.

**Comment by prksn** [comment]
Ühtki muutust ei ole näha: logo on vana, tekst endine, kontaktisiku nimi pole muutunud.

**Comment by andreskytt** [comment]
Hetkeseisuga on kõik Pull Requestides muutunud failid muudetud, ka viimase Pull Requesti oma. Kui midagi on ikka veel puudu, palun viidake failiversioonile, mida avalikult saadaval ei ole ja avage käesolev issue uuesti.
