### ISSUE TITLE
Krattide omnibussi andmed

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#231]
Infoks juurde:
Valim
Küsitlus viidi läbi Turu-uuringute AS igakuise omnibuss-küsitluse raames.

Omnibuss on regulaarselt (kindla ajakava järgi) läbiviidav uuring, mille üldkogumi moodustavad Eesti Vabariigi alalised elanikud alates 15 aasta vanusest (kokku 1 100 881 inimest - ESA, 01.01.2017.a.).

Omnibussi planeeritud valimi suurus on 1000 vastajat. Valim moodustatakse üldkogumi proportsionaalse mudeli alusel.Mudeli aluseks on piirkonnad ning asula suurus (elanike arv), mille alusel valitakse kokku 100 lähteaadressi (valimipunkti). Lähteaadressi valik iga piirkonna sees toimub juhulikkuse põhimõttel rahvastikuregistri aadressiloendite alusel. 

Vastajate valikul lähteaadressil rakendatakse nn „noore mehe reeglit“. See tähendab, et valimisse sattunud aadressil viiakse läbi intervjuu noorima kodusoleva meessoost leibkonna liikmega, kes on vanem kui 15 aastat; kui mehi kodus ei ole, siis noorima naisega. Selline meetod annab neile vastajate kategooriatele, kes tavaliselt harvemini kodus viibivad (nooremad inimesed, meesterahvad), lisatõenäosuse valimisse sattuda, muutes nii empiirilise valimi elanikkonna tegeliku soolis-vanuselise koosseisule vastavamaks.

Täiendavalt rakendatakse vastaja valikul vanuselisi kvoote (igas valimipunktis küsitleti maksimaalselt kaks inimest vanuses 50-59 ning maksimaalselt kaks üle 60-aastast inimest). 

Kokku küsitleti 1010 respondenti. 

2. kuni 15. maini 2019 viidi küsimustik läbi

Kontakt: Ott Velsberg
ott.velsberg@mkm.ee
Work: +372 56 61 4194
[2019 05 OB Tehisintellekt LISA.xlsx](https://github.com/okestonia/opendata-issue-tracker/files/4034068/2019.05.OB.Tehisintellekt.LISA.xlsx)
[2019 05 OB Tehisintellekt TABELID (1).xlsx](https://github.com/okestonia/opendata-issue-tracker/files/4034069/2019.05.OB.Tehisintellekt.TABELID.1.xlsx)

**Comment by tkutsar** [comment]
@infokujur, kes on teabevaldaja e. millise organisatsiooni alla andmestik lisada?

**Comment by infokujur** [comment]
Ott Velsberg MKM

**Comment by tkutsar** [comment]
https://opendata.riik.ee/andmehulgad/kratid-omnibuss/
