### ISSUE TITLE
Perearstide nimistu koosseisud

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#232]
Tuleks viidata portaalis erearstide nimistu koosseisud: https://www.haigekassa.ee/partnerile/raviasutusele/perearstile/perearstide-nimistu-koosseisud

**Comment by tkutsar** [comment]
No reply. Dataset created, will send a follow-up e-mail tomorrow after it's available on site.

**Comment by tkutsar** [comment]
https://opendata.riik.ee/andmehulgad/perearstide-nimistu-koosseisud/
