### ISSUE TITLE
Töövõimetuslehtede andmed

### ISSUE THREAD

**Issue by otuxe** [okestonia/opendata-issue-tracker#233]
Tuleks lisada portaali: https://www.haigekassa.ee/partnerile/raviasutusele/perearstile/toovoimetuslehtede-andmed

**Comment by tkutsar** [comment]
No reply. Dataset created, will send a follow-up e-mail tomorrow after it's available on site.

**Comment by tkutsar** [comment]
https://opendata.riik.ee/andmehulgad/toovoimetuslehed/
