### ISSUE TITLE
Better explanation about licensing

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#25]
Generally better communication about licensing needed.

Need to communicate better - who is the owner of the data?

If it's public, then what applies (reference to Riigiteataja) etc

**Comment by ruizcalleja** [comment]
I totally agree on this issue.

**Comment by boamaod** [comment]
This probably should be part of labels system of #44

**Comment by boamaod** [comment]
By the way, if there is no license specified at the actual site providing the data, sometimes the license is specified (although it might not be a correct one) at Open Data Portal: https://opendata.riik.ee/en

**Comment by andreskytt** [comment]
I'll create a non-technical best practice guide for data publishers in the wiki of this repo. Then get an IP lawyer to take a look at it. There seems to be a contradiction between Estonian and EU copyright/IP law around the licensing of state-generated data. Estonian approach is very liberal, EU is very specific.

**Comment by infokujur** [comment]
Hot topic https://github.com/okestonia/esindus/issues/33

**Comment by infokujur** [comment]
It will be followed here: https://github.com/okestonia/jkan/issues/75
