### ISSUE TITLE
Open Data catalouges - local authorities

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#26]
What's missing?
- Tallinn http://avaandmed.tallinn.ee/
- Tartu http://www.tartu.ee/avaandmed

**Comment by boamaod** [comment]
Pärnu: http://amphora.lv.parnu.ee/amphora_public/?o=39&o2=123029&u=-1&hdr=od&tbs=all

**Comment by boamaod** [comment]
Probably we need to separate the municipalities into their own issues and maybe implement special labels. Tomorrow we can already hold a workshop to fill requests for Tartu, for example.

**Comment by infokujur** [comment]
Labels made, closing. Some already have their issues assigned.
