### ISSUE TITLE
Open licenses for the ESTER library catalogue

### ISSUE THREAD

**Issue by reosarevok** [okestonia/opendata-issue-tracker#28]
The Estonian library catalogue is very data-rich (one of the best catalogues I've seen), but the licensing is quite meh: [For the purposes of copy cataloguing, the data of the online catalogue are freely accessible to all Estonian libraries. Other institutions may copy these data upon agreement with ELNET](http://www.elnet.ee/index.php/e-catalogue-ester/about-the-catalogue).

It should of course ideally be CC0, but *any* sort of clear open licensing would be pretty good already.

**Comment by reosarevok** [comment]
For use cases, other than the obvious, us at [MusicBrainz](https://musicbrainz.org/) would love access to this.

**Comment by infokujur** [comment]
@puik Do you know something about this?

**Comment by infokujur** [comment]
https://github.com/okestonia/esindus/issues/33

**Comment by puik** [comment]
@infokujur I am not familiar with the libraries' stuff...

**Comment by infokujur** [comment]
This topic will be updated here: https://github.com/okestonia/jkan/issues/75
