### ISSUE TITLE
Land Ownership - Open Data Index

### ISSUE THREAD

**Issue by Hillehinsberg** [okestonia/opendata-issue-tracker#3]
Data should include maps of lands with parcel layer that displays boundaries in addition to a land registry with information on registered parcels of land. The following characteristics must be included in cadastral and registry information submitted.

- Parcel Boundaries
- Parcel ID
- Property Value
- Tenure Type

For more information on land ownership datasets and where they're located, check out Cadasta Foundation's Data Overview.

- Parcel boundaries (inc. latitude and longitude)
- Parcel ID
- Property value (i.e. Price Paid, Property Tax Value)
- Tenure Type (ie. leasehold, freehold, protected lands, public lands, customary lands)

http://global.survey.okfn.org/dataset/land

**Comment by andreskytt** [comment]
Please validate available data, comment if something is missing and close if the data is available

**Comment by andreskytt** [comment]
http://geoportaal.maaamet.ee/est/Andmed-ja-kaardid/Maakatastri-andmed-p117.html

"Vastavalt Maakatastriseaduse § 7 lõikele 2 ja Riigilõivuseaduse § 137 on katastri ametlikud väljavõtted maksustatud riigilõivuga."

**Comment by infokujur** [comment]
Maaametil on olemas viide opendata.riik.ee portaali https://opendata.riik.ee/andmehulgad/maa-ameti-avaandmete-portaal/
Palun uuendada infot nii, et opendata.riik.ee-l oleks viidatud ka andmehulgad https://geoportaal.maaamet.ee/est/Andmete-tellimine/Avaandmed/Katastriuksuse-andmed-p610.html

**Comment by tanel2** [comment]
Alates 01.07.2018 on maakatastri andmed avaandmetena allalaaditavad aadressilt https://geoportaal.maaamet.ee/avaandmed Otseviide opendata.riik.ee lehele on lisatud.
