### ISSUE TITLE
Accessible buildings

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/opendata-issue-tracker#31]
It would be good to see what buildings (to start with in Tallinn) are handicap accessible AKA: ramp access, elevator in building, etc... this would be useful for those who may have some sort of disability and are moving to Tallinn, but would otherwise not be able to tell if a given building would be usable for them.

**Comment by andreskytt** [comment]
Next course of action: either find somebody to dive into riha.eesti.ee to see if EHR contains the data or do it myself. Based on that we'll see if the data is even collected anywhere.

**Comment by keeganmcbride** [comment]
As far as I remember this is not in the EHR dataset, I can double check.

**Comment by keeganmcbride** [comment]
My Estonian is still not the best, but from what I can tell none of these columns relate to accessibility. 

Id Ehr Kood Nimetus Seisundi kood Seisundi nimi Kaos Id Peamine KAOS kood Peamine Peamine KAOS Omandi liigi kood Omandi liigi nimii Aadress tekstina kehtiv Rajatis Hoone Maakonna kood Omavalitsuse kood Max Korruste Arv Eh Alust Kp Ajeh Kasutalg Kp Ajeh Kasutlopp Kp Markused Soltumatu Vallasasi Kinnistamise avalduse kp Date Created Date Updated Adsoid Abs 0 Korgus Ehitisalune Maapealne Pind Ehitisalune Pind Esmane Kasutus Koetav Pind Korgus Laius Lift Maht Neto Max 0 Korgus Max 0 Sygavus Pikkus Pind Suletud Netopind Maaaluste Korruste Arv Maht Maaalune

**Comment by tormi** [comment]
@keeganmcbride, you're correct - EHR doesn't contain that data. But I found a webpage which does: http://www.liikumisvabadus.invainfo.ee/?go=webmap

**Comment by tormi** [comment]
This data should be a part of EHR data model in the future..

**Comment by andreskytt** [comment]
@tormi, do you know where they get the info from?

**Comment by tormi** [comment]
> where they get the info from?

By collecting from the field:
- http://www.liikumisvabadus.invainfo.ee/index.php?picfile=42
- http://www.liikumisvabadus.invainfo.ee/index.php?go=ankeedid

**Comment by andreskytt** [comment]
Oh, crowdsourcing, then! Therefore it is probably safe to assume this stuff does not really exist as a dataset. Bugger.

**Comment by keeganmcbride** [comment]
Looking into this a bit further, it looks like Tallinn LV should have this information.

**Comment by keeganmcbride** [comment]
http://www.arcgis.com/sharing/rest/content/items/af5d57b0fa984bf6901f0e8494f2b292/data?f=json

All data for the web map: http://www.arcgis.com/home/webmap/viewer.html?webmap=af5d57b0fa984bf6901f0e8494f2b292 is available at the first link.

**Comment by keeganmcbride** [comment]
@tormi Thanks! Looks like Tallinn is also now working on an accessibility portal with this data according to what I could understand here: http://www.tallinn.ee/05.02.2013-Tallinna-universaalse-disaini-programm-2013-2017-lisa-1

**Comment by tormi** [comment]
Does it? That protocol is from 2013, and www.accessibletallinn.ee is still available for registration ..

**Comment by keeganmcbride** [comment]
Have also seen it here: http://www.tallinn.ee/TSTA_Ule-lavepaku_tegevuskava,-15.03.2016

It seems that something may be happening, but am not 100% sure investigating a bit more.

**Comment by infokujur** [comment]
01.04.2016 Tallinn started to enter information about building to Ehitusregister. Before (and other places) everything is probably on paper.

**Comment by infokujur** [comment]
We need more information, now it's to few.

**Comment by infokujur** [comment]
If there is any data or applications, it can be added here: https://opendata.riik.ee/juhend/
Fast search didn't give any results.

**Comment by otuxe** [comment]
Ligipääsetavuse andmed on meil registris olemas osaliselt (liftid) ning samuti on meil olemas energiamärgiste andmed. Mõlemad andmed on kättesaadav avaandmetena https://avaandmed.ehr.ee/
