### ISSUE TITLE
Real Estate Sales

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/opendata-issue-tracker#36]
It would be beneficial if a dataset existed which was able to show the sale of real estate, the date, and the amount (or at least the amount in a range).

**Comment by tormi** [comment]
Unfortunately, access to that data is restricted (only available to licensed valuers), see http://geoportaal.maaamet.ee/est/Andmed-ja-kaardid/Tehingute-andmebaas-ja-hindamine-p81.html (in Estonian).

**Comment by tormi** [comment]
You can query real property price statistics here: http://www.maaamet.ee/kinnisvara/htraru/FilterUI.aspx

**Comment by keeganmcbride** [comment]
The query tool is nice, but it would still be awesome to have it as an open data set there are many ways in which this data could be used in a positive way.

**Comment by KarinLeivategija** [comment]
Would be great to have price statistics query in a machine readable form.

**Comment by tormi** [comment]
Notified [Andres Juss from Maa-amet](https://www.maaamet.ee/et/kontakt?tid_with_depth[0]=167).

**Comment by tormi** [comment]
Unfortunately, _status quo_ remains:

> 4. mai 2017 14:25 kirjutas Andres Juss <Andres.Juss@maaamet.ee>:
> 
> Tere Tormi
> 
> Kahjuks mul hetkel midagi lisada ei ole. Hinnastatistika päringukeskkonnas andmeid mida teha avaandmeteks ei ole, sest iga kord kui keegi seal midagi pärib tehakse juurdepääsupiiranguga toorandmete alusel uus arvutus. Päringukeskkonna alusel andmete tekitamine ehk kõikvõimalik päringute pidev käivitamine, tulemuste andmebaasi salvestamine ja nende masinloetaval kujul avaldamine eeldab mahukat IT arendust.
> 
> Tervitades
> Andres

**Comment by keeganmcbride** [comment]
We should check with Maaamet again as they have undergone changes.

**Comment by infokujur** [comment]
Info on opendata.riik.ee needs to be updated if info is there: https://opendata.riik.ee/andmehulgad/?organization=maa-amet
