### ISSUE TITLE
Pedestrian, bicyclists and carriders injuries and fatalities (in Cities).

### ISSUE THREAD

**Issue by jubejuss** [okestonia/opendata-issue-tracker#38]
* Places
* When happened, wheather conditions, day-night.
* Description, what happened.
* Descriprion, what are street parameters.
* ...
It is wery useful to know where, why and when accidents happen in traffic.
When that kind of information is accessible, community organizations can make analytics and suggestions to Transportation Department. Or just pay attention, armed with data.

**Comment by keeganmcbride** [comment]
We have traffic accident data here: https://drive.google.com/open?id=0B-uo-u1vqujbR3prUFdYQTZUWnc

**Comment by jubejuss** [comment]
Unfortunately LKF database is carinsurance-centric, so there is very little information about pedestrians and biciclists. Police have data with all accidents and good descriptions too, but this is not public yet.

**Comment by keeganmcbride** [comment]
Yes that is true, having the other accidents as well would be good to know.

**Comment by andreskytt** [comment]
Ministry of Justice claims responsibility for accident data (an agreement with the Police folks) and are working on making the dataset available.

**Comment by infokujur** [comment]
Here: https://www2.politsei.ee/et/organisatsioon/analuus-ja-statistika/avaandmed.dot
But link is broken @ opendata.riik.ee
