### ISSUE TITLE
Bottleneck's in city traffic and effects after remake.

### ISSUE THREAD

**Issue by jubejuss** [okestonia/opendata-issue-tracker#39]
* Traffic volumes in streets – car's volumes, pedestrians volumes, bicyclists volumes, public transportation users volumes.
* Bottleneck's (intersections)
* Changes after street reconstruction or construction

**Comment by keeganmcbride** [comment]
Would also be interested in this data, I think it would be possible to get a non governmental dataset from Waze, @andreskytt would know more.

**Comment by andreskytt** [comment]
Indeed. I will talk to the road authority about Waze data.

**Comment by wipsise** [comment]
Would like to understand the actual safety effects of the works. Crashes, injuries, severe injuries, fatalities, before and after.

**Comment by keeganmcbride** [comment]
http://kindlustus.maps.arcgis.com/apps/Viewer/index.html?appid=abd977aeea074631845cc67bfc3da87d Some of this data is available here.

**Comment by keeganmcbride** [comment]
https://www.mnt.ee/et/ametist/statistika/liiklusonnetuste-statistika Some stuff here as well.

**Comment by infokujur** [comment]
This is epic - it means that information is needed what is gathered from different datasets. Please do open different requests for each dataset what is still missing. AFAIK Tallinna geoportaal has made huge leap. It might be that we do not need much to get the full picture but it needs more of content expert than data expert here to take a look into. https://opendata.riik.ee/andmehulgad/tallinna-geoportaal/
