### ISSUE TITLE
Government Budget - Open Data Index

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#4]
Twitter  Facebook  Google+
National government budget at a high level. This category is looking at budgets, that is the planned government expenditure for the upcoming year, and not the actual expenditure.

- Budget per government department
- Budget per sub-department
- Descriptions for budget sections

http://global.survey.okfn.org/dataset/procurement

**Comment by andreskytt** [comment]
https://www.rahandusministeerium.ee/et/eesmargidtegevused/riigieelarve-ja-majandus/riigieelarve-ja-majandusulevaated Contains excel files for the planned budget for this year and the fulfilment reports for the previous years grouped by ministries
