### ISSUE TITLE
How far is your child's (elementary)school.

### ISSUE THREAD

**Issue by jubejuss** [okestonia/opendata-issue-tracker#40]
* Distances between school and home.
* where are schools and where are homes.
In order to plan schools (or places where one can learn) and reduce traffic demand.

**Comment by keeganmcbride** [comment]
https://info.haridus.ee/Asutused School addresses can be found here for Tallinn
https://enda.ehis.ee/avalik/# should have addresses for all of Estonia.

We are currently building an application which will be able to do this calculation which you asked for at:
https://github.com/keeganmcbride/EstonianRealEstatePilot

**Comment by jubejuss** [comment]
No, no, no – where are schools, that is clear, but what is unclear is from where children actually come to school. I guess this doable partly with help of mobile positioning and "Tallinna ühiskaart" (someday hopefully).

**Comment by keeganmcbride** [comment]
Oh, okay, I understand now what you are saying. Not sure the best way to approach that one. I am sure that schools have an address on file for students so they probably have an understanding of avg distance traveled to arrive at the school

**Comment by jubejuss** [comment]
In near future (hopefully) there will be release of Tallinn bicycle strategy, where is represented that kind of data. Will see what kind it actually is and is it reproduced.

**Comment by andreskytt** [comment]
What can this data be used for: school bus routes, bicycle strategies, traffic planning etc.

@jubejuss Could you please describe the desired data in more detail, maybe provide an example.

**Comment by Hillehinsberg** [comment]
Info from Tallinn LV (Mari Jüssi, project "liikuvuskava": Andmeid, mida saaks jagada on 4000 tallinlase liikumispäevikud ja küsitluse andmestik.
Tallinna kooliõpilaste kooli ja elukohad (nii ebatäpsed kui nad on )
 
Peaks saama valideerimiste ja bussiloendurie andmed, aga need on tasuta ühistranspordi tõttu puudulikud

**Comment by infokujur** [comment]
@jubejuss Something from here? Kredex/Emor (2015) - Questionaire data of 4000 people of Tallinn - how and why people are moving - to map patterns of moving.
https://www.dropbox.com/s/nntxk6bwnhnqlx2/2015%20Tallinna%20uuringu%20tulemused.zip?dl=0

**Comment by infokujur** [comment]
#72 Issue was mapping also some needs. For example green card dump was given. It was anonymized and could be given for analyses for this given purpose.

**Comment by infokujur** [comment]
Tallinn avas kevadel oma geoportaali.
https://opendata.riik.ee/andmehulgad/tallinna-geoportaal/

Kas info on leitav ristates maameti katastriandmeid + Tallinna ruumi andmeid jm registreid? Kui ei ole, siis palun avada andmepäring konkreetse puuduva andmestiku osas.
