### ISSUE TITLE
Ehitisregister - Buildings data

### ISSUE THREAD

**Issue by tormi** [okestonia/opendata-issue-tracker#41]
Buildings data needs to be available on a daily basis, not as a snapshot from the history (2016-01-22 as of now, http://opendata.mkm.ee/ehr/). Also, there is no spatial data about the building boundaries available.

**Comment by keeganmcbride** [comment]
Would be extremely interested in this as well, the available data set is almost unusable as well due to quality issues.

**Comment by boamaod** [comment]
What about data on actual usage of buildings? As far as I know this is gathered by municipalities and there is no single standard how to do it and how to publish the data, is that so? For example Tartu has this kind of directory (about business spaces only):

* http://www.tartu.ee/rent/

As far as I know initiatives like [Ruumiringlus](https://www.facebook.com/ruumiringlus/) are interested in using that kind of data and mapping it with data about demographics etc.

**Comment by tormi** [comment]
You can find live state's buildings portfolio and usage data in #21. This issue is more about the availability of [EHR](https://www.ehr.ee/)'s data. Maybe we should create another issue for countrywide property/facility management data.

**Comment by andreskytt** [comment]
@tormi Yes, please go ahead and create a separate issue for "countrywide property/facility management data". Let's keep this issue focused on improving EHR dataset availability.

**Comment by tormi** [comment]
@andreskytt , done: #47

**Comment by infokujur** [comment]
#31

**Comment by timotoots** [comment]
MKM published it's data set now in a new format which has removed some fields (location coordinates for example). There is also previous version from 2016 available, but it's not updated any more.
Would be great to have the location data also on the update version. Any insights?

http://opendata.mkm.ee/ehr/

**Comment by tormi** [comment]
Yesterday, I met with people from MKM and got the information that a new portal for buildings open data has been launched recently: https://avaandmed.ehr.ee/ !!

An API: https://avaandmed.ehr.ee/api/v1/reports

**Comment by timotoots** [comment]
It's great that MKM made the API! It's a good start, but it could be improved a bit.

Currently it's possible to get only one month of update history at a time. If somebody wanted to know the current state of all buildings, it would take so many API calls. And the e-mail validated queue system is hard to integrate as well.

If the reports would be too big, why not have a static CSV for last year and then use the API to get the updates?

**Comment by timotoots** [comment]
Other thing that could be improved is adding centroid coordinated of the buildings footprints. It would make mapping much easier, currently it means parsing the address.

**Comment by infokujur** [comment]
Current state of art here: https://opendata.riik.ee/andmehulgad/ehitisregister/

**Comment by Kristjan4** [comment]
There isn't any restrictions that you have to download month update history at time. You can specify which time period of data you exactly need and download that information. Coordinates information is also published https://avaandmed.ehr.ee/
