### ISSUE TITLE
Create a system of labels and milestones for the entries

### ISSUE THREAD

**Issue by boamaod** [okestonia/opendata-issue-tracker#44]
So we probably need labels for:

* Themes/topics
* Geographical areas (municipalities, at least bigger ones)
* Progress with the issue (some indication about status)

What else? We can also create milestones to prioritize the issues according to some procedure, that we agree on.

**Comment by infokujur** [comment]
https://github.com/okestonia/Estonian-Open-Data-Issue-Tracker/labels

**Comment by andreskytt** [comment]
The proposal is to use responsible organisations as labels and assign to individual users if specific work is needed. Categories can emerge as well as we do the pruning. Let's document this in README.

**Comment by tormi** [comment]
Maybe we can use [the kanban board](https://github.com/okestonia/Estonian-Open-Data-Issue-Tracker/projects) GitHub is providing for status labelling (backlog / data available / open data available or sth)

**Comment by tormi** [comment]
Official abbreviations for ministeries:

- HTM - Haridus- ja Teadusministeerium
- JUM - Justiitsministeerium
- KAM - Kaitseministeerium
- KEM - Keskkonnaministeerium
- KUM - Kultuuriministeerium
- MKM - Majandus- ja Kommunikatsiooniministeerium
- MEM - Maaeluministeerium
- RAM - Rahandusministeerium
- SIM - Siseministeerium
- SOM - Sotsiaalministeerium
- VÄM - Välisministeerium

**Comment by tormi** [comment]
Re: https://github.com/okestonia/Estonian-Open-Data-Issue-Tracker/issues/44#issuecomment-287082987

Something like this: https://github.com/tormi/open/projects/1

**Comment by andreskytt** [comment]
This would seem to be done: the project is there, have started to assign cards to the silos. @boamaod as OP, close if you agree.

**Comment by tormi** [comment]
Cool! I'd like to get feedback for https://github.com/okestonia/Estonian-Open-Data-Issue-Tracker/issues/44#issuecomment-287130974 as well (use official abbrevs). And I can't close, don't have enough rights to close other's issues ;)

**Comment by infokujur** [comment]
I created those labels - as I didnt know all of them by heart. Ill fix that - fine for me.

**Comment by infokujur** [comment]
@boamaod as OP, close if you agree.

**Comment by infokujur** [comment]
Closing.
