### ISSUE TITLE
Issues for State Open Data Portal should be filed in official issue tracker

### ISSUE THREAD

**Issue by boamaod** [okestonia/opendata-issue-tracker#45]
It might be useful to file at least technical issues about the Open Data Portal (also) in official issue tracker at:

* https://github.com/opendata-ee/opendata.riik.ee/issues

Some issues are technical and about content at the same time, in these cases it is probably useful to crosslink the issue between different issue trackers.

**Comment by andreskytt** [comment]
Reasonable. Let's make a comment on that on the README.

**Comment by tormi** [comment]
Actually, that project is in orphan status currently. @p2tu, could you please give some insights about whether you'll use it or not in the future.

**Comment by boamaod** [comment]
You can file an issue on this issue tracker that issues are not being fixed and commented. :-)

I have to talk to ministry about it anyway, because I promised to fix https://github.com/opendata-ee/opendata.riik.ee/issues/6 for them, if they find their keys to Google Analytics API. It has taken more than month for them now, but I'll contact them, if I have time.

**Comment by andreskytt** [comment]
@boamaod What's the status of this? Shall we close?

**Comment by infokujur** [comment]
If again active, then open again.
