### ISSUE TITLE
Maybe rename the repository with some less baroque name?

### ISSUE THREAD

**Issue by boamaod** [okestonia/opendata-issue-tracker#46]
Using hyphens is crazy enough, maybe just "Open Data tracker" would work? Since it's OK-EE initative, we can also omit "Estonian"? The machine name could be just `opendata-tracker` or something like that?

**Comment by andreskytt** [comment]
Current name is descriptive enough to show up in search. Let's close for now and re-open, if we feel strongly about the issue.

**Comment by boamaod** [comment]
Having machine name with all relevant keywords for title is not SEO but just annoyance for readers or people who see this kind of title in search engines, no? Probably it's also bad from SEO point of view, for example the search for ["estonian open data issue tracker"](http://lmgtfy.com/?q=estonian+open+data+issue+tracker) didn't give reference to this repository for me.

Setting actual title for the repository with means provided by GitHub would make more sense and we need SEO also for Estonian... For example README we created in #23 probably helps more, but now we should also put there something in Estonian.

AFAIK current naming doesn't follow any SEO or [other conventions](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Multiple-word_identifiers), but uses CamelCase and hyphens at the same time for machine name, which is doubling and as such unnecessary. If there is some SEO standard that the current practise uses, please refer to it. By the way, since the keyword Estonia is already in "okestonia", this is also doubled in web address.

I wouldn't be surprised if this repo would be even blacklisted by search engines.

Removing hyphens and/or capital letters from name of repository would be something to start with, but I also suggest shortening it and providing SEO keywords in proper title and README.

My proposal (for discussion):

Web address: https://github.com/okestonia/opendata-issue-tracker
Title: Estonian Open Data issue tracker / Eesti avaandmete turuplats    Link: opendata.ee/tracker

If we provide a link, a post on opendata.ee or ee.okfn.org is also needed, first can be done through pull request to https://github.com/okestonia/okestonia.github.io, second one is Wordpress.

**Comment by andreskytt** [comment]
Let's make a decision on this during the next grooming session

**Comment by boamaod** [comment]
Well, I think simply putting a title to repository is essential and should be done ASAP. I'll just put something there, otherwise I cannot even refer it in [post-truth hackathon](http://hack24.ut.ee/) invitations, currently it just gives an impression that it's something totally random.

**Comment by andreskytt** [comment]
Done
