### ISSUE TITLE
https://riha.eesti.ee should be part of open data ecosystem

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#53]
- What data can be opened, could be marked that way in the profile of the given system.
- Status of that potential dataset could be marked (ex missing, in process, done - with link)

Random example of one profile: https://riha.eesti.ee/riha/main/inf/eelnoude_infosusteem 

That would enable possibility to generate open-data catalogues from RIHA

**Comment by tormi** [comment]
This is in the works: https://github.com/e-gov/RIHA-Publisher

**Comment by andreskytt** [comment]
@tormi, RIHA-Publisher does not do anything else but replace existing RIHA. What @infokujur is requesting here is that data field can be marked as openable, open or closed. IMHO this would yield very little useful information as vast majority of data in the registries, the primary data, is closed by definition as it is about citizens. 

You cannot and should not open up the penalty registry as basically all the fields and records are highly sensitive. Statistics, the secondary data, created from this sensitive data should be open, however.

**Comment by tormi** [comment]
@andreskytt, got it wrong then. But there is a point in @infokujur's request. Namely, it's very wasteful to have RIHA for x-road services and then https://opendata.riik.ee/ for randomly selected opendata. Open data services should be treated at the same level as x-road services.

**Comment by infokujur** [comment]
Having the meta data on RIHA would give us possibility to pull the whole list of open data / to be opened data. For sure delicate data should be marked accordingly.
@tormi - yes, that what I meant. RIHA would be the full list and open data list would be the random list.

**Comment by andreskytt** [comment]
@tormi You are right. But the processes for both are completely different in the organisations. It is my vision that eventually publishing of open data APIs can be done with the same ease, discoverability and fluidity x-road services are published but this is still way off. 

RIHA will be opening their datasets, this is in progress but merging of and x-road is not on the horizon as far as I can see. Close if there is no further immediate action possible
