### ISSUE TITLE
Organic farming registry

### ISSUE THREAD

**Issue by tormi** [okestonia/opendata-issue-tracker#59]
Organic farming registry's farmer's open data (_https://www.agri.ee/et/avaandmed > Mahepõllumajanduse register > Mahepollumajandus.klient.csv_) doesn't contain `company's business register's registry code`. Therefore, using this data is very hard and error-prone (see https://github.com/honeymarket/mesilad.mesindus.ee/issues/37#issuecomment-290091097 for example).

**Comment by infokujur** [comment]
Nothing changed here.

**Comment by jtali** [comment]
We will add company's business register's registry code. I will be done about by the end of the month.

**Comment by tormi** [comment]
Thank You, closing!
