### ISSUE TITLE
API / dataset for all Riigikogu votes

### ISSUE THREAD

**Issue by taivop** [okestonia/opendata-issue-tracker#60]
The data is already available on riigikogu.ee, but only as websites that need to be scraped to get a full dataset.

I'd like to see, at minimum:

* all bills ever voted on
* how each member of Riigikogu voted

And if possible:

* attendance (when was a member of Riigikogu present)
* transcripts of the sessions (which again already exist on the website)

(this seems somewhat related to #30 but I think that issue doesn't cover the voting data)

**Comment by andreskytt** [comment]
I have seen the data scraped, trying to track it down

**Comment by taivop** [comment]
I was in contact with Riigikogu kantselei (Janek Solodin) and:
* I now have an up-to-date database dump; will upload and link here soon
* they are planning to release a JSON API (first testing to be started in May)

So I guess this issue is low priority now.

**Comment by taivop** [comment]
Votes: `haaletused.json.gz`. Download: [mega.nz](https://mega.nz/#!5RU1RAYb!sUKXljnCDcGaslv_p_6MqSrcHkX7DyAlyG3V4tMpGgo) (6.2MB)

**Comment by taivop** [comment]
Transcripts: `stenogrammid-13_04_17.sql.gz`. Download: [mega.nz](https://mega.nz/#!FQdwFLAb!jmRNm-usrtS6K85CWWGQHhtr5SXqdA_fG_5TveZ6-lE) (172MB)

**Comment by tormi** [comment]
> they are planning to release a JSON API

@taivop, by using http://jsonapi.org/ ? 

The agencies current practice of implementing API's is very inconsistent and to my knowledge there is no clear rule or even advice from RIA nor MKM about this. @andreskytt , what do you think, can this be improved?

**Comment by boamaod** [comment]
We already played with the data a bit:

* https://hackdash.org/projects/590c99334545fa01a8db1638

**Comment by ottomattas** [comment]
Just opened the API's testenvironment to the public. It is only temporarily up and the documentation on it is minimal but I hope you can find something worth looking at.

https://aavik.riigikogu.ee

**Comment by tormi** [comment]
re: https://aavik.riigikogu.ee/api/ems/v1/raml/ems-api-v1.html

> Teeme veel viimaseid parendusi lõpplahendusele ning andmestruktuuridele. Kui on huvi koostööd teha või mõtteid jagada, kirjuta vastutavale süsteemihaldurile aadressil otto.mattas@riigikogu.ee.

@ottomattas , have you considered using [JSON API](http://jsonapi.org/) spec?

**Comment by ottomattas** [comment]
@tormi, I have. There are some concerns, though. We are trying to work with RIA on this matter and they today implicitly suggest using OpenAPI Specification which in turn may not be fully compatible with JSON API spec yet. (Priit Parmakson's not yet finalised guide for national API's: https://agiil.github.io/IT/API#api-spetsifitseerimine).
The proposed usage (or scope of it) of Google API's design guide for Estonia's Open Data solutsions is another matter altogether.

But the idea of using [JSON API](http://jsonapi.org/) is totally worth a mention. I will be taking another look at it when official JSON Schema is added to OpenAPI 3.0 [repo](https://github.com/OAI/OpenAPI-Specification/tree/OpenAPI.next).

**Comment by boamaod** [comment]
@ottomattas, there is probably some historical reason for having no formal agendas before 2012 autumn?

* https://www.riigikogu.ee/tegevus/paevakorrad-ja-protokollid/?startDate=21.04.2010 // https://aavik.riigikogu.ee/api/ems/v1/agenda/plenary?date=21.04.2010

Compared to:

* http://stenogrammid.riigikogu.ee/et/20100421/ (and data dump above `paevakord` table `idistung=1187`)

**Comment by ottomattas** [comment]
@boamaod, yes. Said data has different data structure comparing to other formal agendas (after autumn 2012) because of the development of internal systems at that time. It needs some work standardising the data to be decently published on the parliament's webpage ([https://www.riigikogu.ee](https://www.riigikogu.ee/tegevus/paevakorrad-ja-protokollid)) and effectively through the API.

We are working on the issue of data standardisation as we speak, at the moment voting data is in focus. Hopefully, formal agendas get the treatment as well. (No plan to do so has been set yet, though.)

**Comment by boamaod** [comment]
@ottomattas, [our hackathon experience](https://github.com/infoaed/openprogress) was that agenda links together most of other data and this might be a reason for prioritising. :)

**Comment by tormi** [comment]
Is `limit` parameter working for all resources? https://aavik.riigikogu.ee/api/ems/v1/document-hierarchy-tree?limit=1 seems to ignore it. And can I use pagination?

**Comment by tormi** [comment]
@ottomattas, can I [fetch relationships](http://jsonapi.org/format/#fetching-relationships) in a consistent way? For example, _give me [user](https://aavik.riigikogu.ee/api/ems/v1/raml/ems-api-v1.html#users__uuid__get)'s [events](https://aavik.riigikogu.ee/api/ems/v1/raml/ems-api-v1.html#calendar_events_get)_.

**Comment by ottomattas** [comment]
@boamaod, thanks for the feedback. This is really valuable input, we'll keep it mind. 👍

@tormi, at the moment `limit` parameter is only working for specific resources as we are still working on standardising the solution. Also, [/document-hierarchy-tree](https://aavik.riigikogu.ee/api/ems/v1/document-hierarchy-tree?limit=1) gives only one result so there is no point in adding `limit`/`skip` etc explicitly for the parameters' functionality. Holding up to the standard is a legitimate reason, though.

I will introduce @indrekmaask as the developer for the parliament's open data project. Hopefully he can answer any technical questions (including the query about pagination from @tormi) more specifically.


As it seems there's an interest for parliament's open data project in general, maybe I should start an issue tracker of our own to keep track of the proposed ideas and related issues?

**Comment by Hillehinsberg** [comment]
@ottomattas and @indrekmaask  - thanks for the work done and the input here!
I suggest to keep the dialogue going on here, as   lond as the interested users have already found this track. The link was  disseminated to all Garage48 participants and  wider group of  those who are potentially interested  in similar issues.

**Comment by boamaod** [comment]
@ottomattas, having special `Riigikogu` label to sort out relevant issues might be enough? I see that it already exists with one issue attached, added also to current issue.

**Comment by tormi** [comment]
@ottomattas, thanks! 

> maybe I should start an issue tracker of our own to keep track of the proposed ideas and related issues?

Yes, please! This place should only deal with onboarding and status of open data availability. When open data is available, we should point users to data and label issue accordingly ("Open data available" at https://github.com/okestonia/opendata-issue-tracker/projects/1). @Hillehinsberg, could you please label this issue accordingly? If data provider has it's own issue tracker, we should close the issue here and provide the path to app's tracker.

See also [CONTRIBUTING.md](https://github.com/okestonia/opendata-issue-tracker/blob/master/CONTRIBUTING.md) (point 3) and #71.

**Comment by indrekmaask** [comment]
Hey all!
I'd like to point out that the current API is written specifically for the website and not for public use. There's a lot to be done in order to conform to proper public API standards, starting with documentation, better defined resources, data representation etc.

**Comment by boamaod** [comment]
@ottomattas and @indrekmaask, it might be smart to use (or at least try to mimic) some of the existing standards for decision body data representation APIs, since it might make implementing 3rd party tools/code much easier. I'm not terribly aware of such standards, but looking at Finland as leader of Open Data in our region might be a good start. For example in 2016 six Finnish municipalities created [a common standard](https://github.com/6aika/api-paatos/blob/master/README.md#open-decision-api-6aika) exactly for that, it might be useful to discuss their experience before making final decisions. Sharing tools/code on shores of Finnish Gulf would be really promising option for governments/municipalities as well as journalists, data analysts, application developers, activists etc.

**Comment by ottomattas** [comment]
Thanks for the input! You have helped us forward with the technical aspects. Also, showing active interest in what we do and are trying to accomplish, gives our organisation much needed attention regarding open data - this shows decision makers the subject is really relevant and worth pursuing. Hopefully the collaboration leads to something wonderful in the end!

Let's keep the momentum going: https://github.com/riigikogu-kantselei/api (there's no code yet, only a public issue tracker).

**Comment by tormi** [comment]
Time to close this one?

**Comment by ottomattas** [comment]
I believe so as the initial issue seems to be solved. Datasets requested in the issue are available.

Also, anybody interested in further developments can make their way to the parliament's [repository for Open data API](https://github.com/riigikogu-kantselei/api) as said before.

**Comment by infokujur** [comment]
Palun uuendada infot opendata.riik.ee https://opendata.riik.ee/teabevaldajad/ @marmoluik
Siis saame lõimu sulgeda.

**Comment by marmoluik** [comment]
Andmed on opendata.riik.ee keskkonnas uuendatud @infokujur

**Comment by infokujur** [comment]
Väga hea! Kas nüüd tulevad nad juba otse, või on seal veel ca kuu pikkune vahefaas?

**Comment by marmoluik** [comment]
@infokujur Kuna nüüdseks on API _lives_, siis tegemist on _live_ andmetega.

**Comment by infokujur** [comment]
_Originally posted by @janesmae in https://github.com/riigikogu-kantselei/api/issues/13#issuecomment-446573489_
@marmoluik  Ehk see küsimus on ka lahendatud?

**Comment by janesmae** [comment]
> _Originally posted by @janesmae in [riigikogu-kantselei/api#13 (comment)](https://github.com/riigikogu-kantselei/api/issues/13#issuecomment-446573489)_
> @marmoluik Ehk see küsimus on ka lahendatud?

Jah. Riigikogu Kantselei avaandmete API on nüüd toodangus ja asub: api.riigikogu.ee (vastavalt infole Avaandmete portaalis).

- https://opendata.riik.ee/andmehulgad/Riigikogu-veebi-avaandmed/ 
- https://www.riigikogu.ee/avaandmed
