### ISSUE TITLE
Organic Area Map

### ISSUE THREAD

**Issue by tormi** [okestonia/opendata-issue-tracker#62]
Would love to use [Organic Area Map](http://www.organicestonia.ee/et/tana-esitletakse-maa-ametis-esimest-maheala-kaarti/) as a background layer at [mesilad.mesindus.ee](https://mesilad.mesindus.ee/#4/58.63/24.98/alus-kobarad). Preferably as [WFS service](http://docs.geoserver.org/latest/en/user/services/wfs/) capable of outputting [GeoJSON](http://docs.geoserver.org/latest/en/user/services/wfs/outputformats.html#json-and-jsonp-output), but other options are ok as well :)

Ref: https://github.com/honeymarket/mesilad.mesindus.ee/issues/24

**Comment by tormi** [comment]
@tkardi & Co, please consider adding this as a WMS/WFS service to https://github.com/e-gov/kem-gsavalik ;)

**Comment by tkardi** [comment]
Talked to some people from the Land Board - the dataset is actually owned by PMA (Põllumajandusamet). But it lacks spatial data, only references to PRIA's parcels or Land Board's cadastral units are kept. PRIA's land parcels' vector data should be open, cadastral data sadly not.

Maybe someone from PMA could elaborate on current state and future plans.

**Comment by infokujur** [comment]
Labeling accordingly.
(If anyone will identify data owner - please tag me or other owner and we'll tag accordingly)

**Comment by tormi** [comment]
@infokujur , according to http://www.organicestonia.ee/et/tana-esitletakse-maa-ametis-esimest-maheala-kaarti/,

> **Maa-amet**i, **Põllumajandusamet**i ja **Organic Estonia** koostöös valminud kaardirakendus annab ülevaate 2016. aastal tunnustatud mahepõllumajanduslikust tootmismaast ja taotletud mahedast korjealast.

> Uut mahealade kaarti ja edasisi samme mahedama Eesti poole liikumisel tutvustavad Maa-ameti geoinformaatika osakonna juhataja Mariliis Aren, Põllumajandusameti mahepõllumajanduse osakonna juhataja Anu Nemvalts ja Organic Estonia eestvedaja Krista Kulderknup.

**Comment by infokujur** [comment]
Good news! Link to data please :).

**Comment by infokujur** [comment]
#51

**Comment by infokujur** [comment]
@jtali - palun uuendage infot opendata.riik.ee-l ja viidake siia, kui on lingitud. Siis saame selle lõimu kinni panna.

**Comment by jtali** [comment]
@infokujur link on nüüd olemas : https://opendata.riik.ee/andmehulgad/mem-mahe/. Selle lõimu võib nüüd kinni panna.
