### ISSUE TITLE
Tark tee - Information on conditions on Estonian public roads

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#64]
Application here: https://tarktee.mnt.ee

Apparently there should be also the data but links in this excel are broken:
https://docs.google.com/spreadsheets/d/11cuVu18bBLZpVOdDUVDYwsneXwOeCgdJsOAC3WJUkxQ/edit#gid=0

**Comment by infokujur** [comment]
#39 Connected topics

**Comment by wipsise** [comment]
There is a link to a table data, but there could be more useful data shown like coordinates. 
http://tabel.tarktee.ee/liikluspiirang.php

**Comment by tkardi** [comment]
There's also some (incl spatial) data available through the TarkTee's agserver's REST API https://tarktee.mnt.ee/arcgis/rest/services/avalik

**Comment by infokujur** [comment]
People are happy, everything looks good here.
