### ISSUE TITLE
http://opendata.mkm.ee/ broken links

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#67]
http://opendata.mkm.ee/ - should fix some broken links.

**Comment by infokujur** [comment]
Broken links still there.

**Comment by keeganmcbride** [comment]
@infokujur What broken links are present?

**Comment by infokujur** [comment]
@keeganmcbride http://opendata.mkm.ee/MKM http://opendata.mkm.ee/MNT http://opendata.mkm.ee/RIA http://opendata.mkm.ee/TKA http://opendata.mkm.ee/TJA

**Comment by infokujur** [comment]
This info here https://opendata.riik.ee/andmehulgad/?organization=majandus-ja-kommunikatsiooniministeerium-mkm is not matching http://opendata.mkm.ee/ .

**Comment by Kristjan4** [comment]
It would be wise to close this issue. We are already redirecting our users to Avaandmete portaal : https://www.mkm.ee/et/avaandmed
