### ISSUE TITLE
Contents of the water supply in Tallinn

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#68]
Data is there but not opened and concrete link is broken:
http://www.tallinnavesi.ee/images/stories/%C3%9Clemiste_vee_kvaliteet_2015.pdf

Relates #17 Is Tallinn covered? Somebody needs to check.

**Comment by keeganmcbride** [comment]
http://vtiav.sm.ee/index.php/?active_tab_id=JV This should be something.

**Comment by keeganmcbride** [comment]
http://vtiav.sm.ee/index.php/?active_tab_id=A Avaandmed here.

**Comment by keeganmcbride** [comment]
This is in open data portal, but it is a bit outdated.
