### ISSUE TITLE
Issues workflow

### ISSUE THREAD

**Issue by tormi** [okestonia/opendata-issue-tracker#71]
What's your opinion about how to govern issues where holder of the information has opened repo at GitHub and is willing to cooperate? I propose we then move the discussion there and only change the status of the issue (project's column) here.

Ref: https://github.com/e-gov/kem-gsavalik/issues/7#issuecomment-297826706

**Comment by tormi** [comment]
By referencing from holder's issue we automatically have it's status updated here like this:

![screenshot from 2017-04-28 10-23-14](https://cloud.githubusercontent.com/assets/146800/25518521/c511ce94-2bfc-11e7-85f1-11c117ffe2bc.png)

**Comment by infokujur** [comment]
I created a label "in progress (data owner)" and also column in the project where the issue can be moved. Please close if agreeing.

**Comment by infokujur** [comment]
Example #59

**Comment by infokujur** [comment]
More - If then data is available, then issue will be closed from our side. Also we have to figure out, how to get all the data listed in opendata.riik.ee or some other list.

**Comment by tormi** [comment]
Let's wait for other reactions before closing ;) And, maybe we should add [CONTRIBUTING.md](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) where we explain the workflow. 

BTW, I'm not sure if #59 is in the works yet ;)

**Comment by infokujur** [comment]
It would be great if somebody takes that info organizing. All elements are already here more or less.

**Comment by tormi** [comment]
Workflow enhancement from the data owner's POV: https://github.com/e-gov/kem-gsavalik/pull/9

**Comment by andreskytt** [comment]
Sounds reasonable. Added a CONTRIBUTING.md file, close if sufficient

**Comment by tormi** [comment]
:+1:
