### ISSUE TITLE
Challenge: Make personal data handling more understandable!

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#73]
**keywords: personal data, awareness, knowledge, easily understandable infrastructure, regular people, transparency**

Did you again agree to the terms & conditions without reading? Do you feel like somebody else is benefitting from your data? This challenge focuses on making personal data usage more transparent and understandable to average person. Let’s help end-users understand better, how their personal data is used! Let’s make it possible to give a more informed consent to the nice services we’re using! Let’s help service providers establish a more trusted relationship with the users with transparent data usage applications!

Award: 3-day passes for the MyData2017 conference for the full winning team

Challenge is supported by MyData2017 conference team & partners

**Comment by joellimberg** [comment]
For reference, the Estonian personal data protection act: https://www.riigiteataja.ee/en/eli/507032016001/consolide

**Comment by joellimberg** [comment]
test comment, please ignore

**Comment by infokujur** [comment]
#74 Related (if we talk only about document registries)

**Comment by infokujur** [comment]
Needs better infomaterials on opendata.riik.ee Issue opened here: https://github.com/okestonia/jkan/issues/67
