### ISSUE TITLE
Challenge: Estonian Data Protection Inspectorate - How to ensure that privacy is protected?

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#74]
**Please link here all relevant info/data sources etc!**

**Descritpion:**
All Estonian government agencies must publish their document registries and they usually do. Occasionally, however, the published documents and metadata by mistake contain sensitive personal information that should not be published. This is a major obstacle in making document registries machine readable en masse. The challenge, should you accept it, is to figure out ways to trawl common document registry solutions deployed in Estonian public institutions detecting possible privacy violations. Good luck!

**Comment by ottomattas** [comment]
To help tackle this challenge, I just opened the parliament's (Riigikogu) API's test-environment to the public. It is only temporarily up and the documentation on it is minimal but I hope you can find something worth looking and picking at.

There will be even more data on live-environment soon if you strike an idea worth pursuing further.

https://aavik.riigikogu.ee

**Comment by infokujur** [comment]
Dokumendiregistrite teema on avatud siin:
https://github.com/okestonia/opendata-issue-tracker/issues/140
