### ISSUE TITLE
Challenge: OpenGovIntelligence, Innovation in Real Estate (MKM + TUT joint project)

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/opendata-issue-tracker#77]
GitHub Repo: https://github.com/OpenGovIntelligence/EstonianRealEstatePilot 

The Estonian pilot program is one of 6 pilot programs being carried out by the OpenGovIntelligence project. This pilot program is being carried out by The Estonian Ministry of Economic Affairs and Communications and Tallinn University of Technology.
To this end, we also believe that new services can be built in cooperation with other stakeholders outside of the governmental sector. Many datasets have been cleaned and made available in this repository, some of the datasets may even be visualized (car crash data, addresses, schools, kindergartens). At the Garage48 hackathon two main options exist: work with and improve the initial functionality, or feel free to use the initial shiny UI for your own geospatial data. Also, please not the demo is a work in progress and still quite buggy. 

Datasets are available to download here: https://github.com/OpenGovIntelligence/EstonianRealEstatePilot (nb! car crash data is not correct, use the RDS data in the /tree/master/applicationDevelopment/datasets")

Datasets which have not been cleaned may be found here: https://github.com/OpenGovIntelligence/EstonianRealEstatePilot/tree/master/OpenDataSetsNotCleaned Data is crime data by type, year, and linnaosa in Tallinn as well as bus stops/routes

UI may be found here, https://github.com/OpenGovIntelligence/EstonianRealEstatePilot/tree/master/applicationDevelopment

Demo is here: innovationinrealestate.shinyapps.io/applicationdevelopment

**Comment by infokujur** [comment]
@keeganmcbride It would be great if You go through all issues and refer here all what can be immidiately used by this pilot.

**Comment by keeganmcbride** [comment]
@infokujur can you expand on this? Most of the issues are requests for data, so not sure how the pilot could use data that doesn't exist? I may be misunderstanding.

**Comment by infokujur** [comment]
@keeganmcbride It would be great if we can point out data what can be instantly used, when opened. One of the main focus of this issue tracker is to identify these kind of sets.

**Comment by andreskytt** [comment]
@keeganmcbride has acquired data that is not published elsewhere and made it available via their repo

**Comment by Hillehinsberg** [comment]
Also #47

**Comment by infokujur** [comment]
#72 will be a connection here.

**Comment by andreskytt** [comment]
@keeganmcbride what's the status here, do we have any new datasets to publish or requests for the authorities?

**Comment by infokujur** [comment]
PPA set to link.

**Comment by keeganmcbride** [comment]
@andreskytt I think the only new data set is the one that has been released by the PPA. The only other datasets that people have asked me about are noise and pollution data for Tallinn, any sort of environmental open data (this would be stuff like pollen or allergens I guess in addition to the aforementioned ones), and the building accesibility data, but AFAIK this does not exist.

**Comment by infokujur** [comment]
This project has its own place here: https://github.com/keeganmcbride/realestatepilot/issues
If there are some concrete datasets needed, please open separate issue per dataset or comment and reference already existing ones.
