### ISSUE TITLE
 Challenge: Value added solutions for merchants or payment card users

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#80]
SEB makes available representative dataset of card payment transactions with merchant category and approximate location information. Such data give insights for example to customer payment behavior as well as merchant category business volumes in the region. For privacy reasoning the customer as well as merchant information is anonymized.
We invite to propose value added solutions to merchants and/or to card users. Based on data insights, we expect proposals of business ideas and prototyped solutions providing value for merchants or card clients.
SEB offers to a winner team possibility to develop further the prototype in inspiring environment of newly established Innovation Center.
About our data. The dataset consists of about 3 months card payments done by about 30 000 active card users only to merchants located in Estonia (MerchantType = ‘POS’) or internet based merchants (MerchantType = ‘ECOM’) in all countries. All sums are converted to EUR. Altogether it is about 4 million single transaction lines. 

The card transactions dataset consists of following information:
Card user ID (private customers, anonymized),
Payment amount,
Payment date (expressed as day number from the beginning of period),
Merchant ID (merchant’s company registration code, anonymized),
Merchant terminal ID (merchant’s terminal ID, anonymized),
Merchant location (City or County),
Merchant country code,
Merchant type (‘POS’-merchants using payment terminals, or ‘ECOM’-web shop merchants),
Merchant category code (MCC, defining the merchant’s area of activity).

In addition, the following basic data on card users is given (as a separate table):
Card user ID,
Card user communication language (0 – Est., 1 – Engl., 3 – Rus.),
Age (with intervals of 5 years: 0 = 0-4 yrs, 1 = 5-9 yrs, 2 = 10-14 yrs, 3 = 15-19 yrs etc.),Card user (City or County),
Card user residence area (City or County)

The merchant codes (MCC) are related to code descriptions (in a separate table):
Merchant category code (MCC),
Corresponding merchant’s activity area description.

**Comment by McSim** [comment]
There will not be any info about merchant. Only its category. The payer will be anonimized. But what about any additional info about him? Sex, age, education,..

**Comment by signaltovlad** [comment]
Exactly. Kindly asking to specify data parameters, that would be given? It's hard to state a challenging hypothesis for the hackathon without knowing the details of data, that we will be working with.

**Comment by infokujur** [comment]
@McSim @signaltovlad Updated initial comment with new info.

**Comment by infokujur** [comment]
Aint no open data here in the future.
