### ISSUE TITLE
Remove detailed information about the events from readme

### ISSUE THREAD

**Issue by tormi** [okestonia/opendata-issue-tracker#82]
I suggest removing detailed information about the events from project's readme (after the hackathon), this is not sustainable in the long run. Need to think about the alternatives.

**Comment by infokujur** [comment]
@tormi Agreeing

**Comment by tormi** [comment]
Thanks! Maybe create events folder with `eventname.md` page for every event and link there from readme or sth.

**Comment by infokujur** [comment]
Done.
