### ISSUE TITLE
Lessons learned about the opendata development projects

### ISSUE THREAD

**Issue by tormi** [okestonia/opendata-issue-tracker#83]
It would be interesting to analyze [the past and ongoing opendata development projects](https://www.ria.ee/ee/jooksev-voor-avaandmed-ja-andmeanaluus.html) and learn from it:
- Is the [current guidance](https://www.ria.ee/public/Arhitektuur/Avaandmete_loomise_juhend.pdf) good enough for agencies?
- Is the achieved output meeting the customer's real needs?
- What can be improved?

@andreskytt , maybe RIA can provide some statistics about such projects?

**Comment by tormi** [comment]
Ok, here are some answers: 
- https://www.slideshare.net/AndresKtt/api-first-government#9
- https://agiil.github.io/IT/API

**Comment by andreskytt** [comment]
As of 02.02.2018 OKFEE has been granted responsibility for open data development in Estonia and to improve this. More news coming soon in this issue tracker and in other channels.

**Comment by infokujur** [comment]
We'll keep it updated here: https://github.com/okestonia/opendata-issue-tracker/issues/88

**Comment by infokujur** [comment]
Juhendite koostamine on teemaks ja sellest on ülevaade portaali kasutajate juhendite loomise issues: https://github.com/okestonia/jkan/issues/67 Jätkame seal.
