### ISSUE TITLE
Avaandmete töögrupp: Ülevaated avaandmete olukorrast ja plaanidest / Overviews about open data developents in public sector

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#90]
Edit: /Teema jääb avatuks, kuni on tekkinud hea hulk ülevaateid avaandmete kohta.
Järgmise sammuna on plaan seda sama infot jagada andmekasutajate hulgas - selleks et tekiks dialoog ja arusaam, kas kogukonnal on andmete vastu huvi. /

22.03 avaliku sektori avaandmete töögrupi kohtumise ettevalmistavad materjalid palume viidata siia teemasse.

07.05 kohtumisel jätkame korjet.

Projekt "Avaandmete kasutamise edendamine" viiakse ellu Majandus- ja Kommunikatsiooniministeeriumi tellimusel EL struktuuritoetuse toetusskeemist "Infoühiskonna teadlikkuse tõstmine", mida rahastab Euroopa Regionaalarengu Fond. Hanke tulemusel viib projekti tegevused läbi MTÜ Open Knowledge Estonia.

**Comment by arvotaar** [comment]
Maksu- ja Tolliamet on avaandmetena kättesaadavaks teinud Eesti Tollitariifistiku: https://opendata.riik.ee/et/dataset/eesti-tollitariifistik_01022018
Lähiajal ei plaani midagi rohkemat avaldada seoses maksu- ja ärisaladuste kaitsmise kohustusega.

Edu soovides,
Arvo Taar
Maksu- ja Tolliamet
e-post: arvo.taar@emta.ee
mob. 5283054

**Comment by koit** [comment]
Rahvusarhiiv avaldas 01.01.2015 avaandmetena arhiivikirjeldused ehk arhivaalide metaandmed (pealkirjad, kuupäevad jmt). Andmed on nii analoog- kui digiarhivaalide kohta. Digiteeritud arhivaalide puhul on avaandmetes ka viited kujutiste failidele.

Andmestik katab lisaks Rahvusarhiivile ka teisi asutusi, kes hoiavad oma arhiivikirjeldusi Arhiivi Infosüsteemis AIS (Tallinna Linnaarhiiv, Narva Linnaarhiiv, Ajaloomuuseum jt).

Andmed on esitatud kahes XML-vormingus: RDF ja apeEAD. Andmemaht on u 9 mln kirjeldusüksust. Avaandmed ja nende vormingu täpsed kirjeldused on kättesaadavad Rahvusarhiivi portaalis http://opendata.ra.ee ja riigi portaalis https://opendata.riik.ee/dataset/rahvusarhiivi-arhiivikirjeldused.

Litsentsiks on metaandmetel CC0 ja digikujutistel CC-BY-SA.

**Comment by marmoluik** [comment]
Riigikogu Kantselei poolt on avaldatud [API dokumentatsioon](https://aavik.riigikogu.ee/api/ems/v1/raml/ems-api-v1.html), [Public issue tracker for Open data API](https://github.com/riigikogu-kantselei/api) ja [Vabariigi Valimiskomisjoni valimiste avaandmed](https://opendata.riik.ee/et/dataset/valimiste-avaandmed).

Värskelt on valminud uute teenuste API dokumentatsioon, milles sisalduvad teenused on alles testimisel. Kuna kõik teenused, mis APIs sisalduvad, ei ole avalikud, siis on vajalik peegelserveri loomine API tarbeks, mis kuvab välja vaid avalikud teenused. Hetkel see meil puudub ning seetõttu on vajalik avaandmete jaoks täiesti uue kihi loomine.

Heade soovidega
Marmo Luik
Riigikogu Kantselei
e-post: marmo.luik@riigikogu.ee

**Comment by priitraspel** [comment]
Kuna me Sotsiaalministeeriumi (SoM) haldusalas tegeleme ainult väga isikustatud andmetega, siis meie  avaandmed saavad olla ainutl "tuletatud andmed". SoM haldusalas on avaandmetena käsitletavaid üllitisi Tervise Arengu Instituudil (TAI) ja Terviseametil.
TAI raportid seda päris ei ole, kuna puudub masinloetav vorming. Tegemist on regulaarselt avaldatavate analüüsi tulemustega, mis sisaladavad tabeleid ja graafikuid.
Terviseametil on riigi avaandmete portaalis 25 erinevat andmevalimit XML-kujul.

Parimat,
Priit Raspel
Tervise ja Heaolu Infosüsteemide Keskus
priit.raspel@tehik.ee

**Comment by usinisalu** [comment]
Eesti Rahvusraamatukogu on "oma" andmeid regulaarselt avaldanud alates 2017 aastast alates. Avaandmed ja vormingute täpsed kirjeldused on kättesaadavad Rahvusraamatukogu avaandmete lehel [http://data.digar.ee](http://data.digar.ee) ja riigi portaalis [https://opendata.riik.ee/et/data/search?q=Rahvusraamatukogu](https://opendata.riik.ee/et/data/search?q=Rahvusraamatukogu) 

Andmed on avaldatud XML kujul ja MARC21-vormingus ning neid on võimalik alla laadida kui ka jooksval pärida üle OAI-PMH protokolli.

Lahedat päeva jätku
Urmas Sinisalu

Eesti Rahvusraamatukogu
Raamatukoguteenuste arenduskeskus
@urmas@nlib.ee

**Comment by puik** [comment]
@usinisalu kui natuke norida, siis [**OAI-PMH**](https://www.openarchives.org/pmh/) ei ole just päris *jooksvalt pärimise* protokoll ;)

**Comment by usinisalu** [comment]
@puik See on tõlgendamise küsimus kui muudatuste (uute+muudetud+kustutatud andmete) pärimine kuupäeva ja/või seti alusel pole jooksev vs. kõigi andmete uuesti alla laadimine ühe portsuna, siis võtan sõnad tagasi. Tegemist ei ole tõesti "klassikalise" API/SPARQL päringuga kus saan ise määratleda ja vabalt valida päringu tingimusi ning tulemust küsida vabalt valitud formaadis, selles mõttes kommentaar õige!)

**Comment by infokujur** [comment]
Töögrupi kohtumise kokkuvõte: https://docs.google.com/document/d/1773WeP1op-G7vFJE60Hfz73Vr60HOwIpcohNwMVvOG4/edit#

Võib dokumenti kommenteerida, aga parem leidke/tehke iga teema jaoks eraldi _issue_. Erinevaid teemasid oli tõesti palju. Nüüd on vaja leida fookused ja minema hakata.

**Comment by boamaod** [comment]
Siit on leitavad mõned sõltumatud kirjeldused avaandmete seisust eri asutustes (eesmärk pole anda kõigi asutuste kohta ülevaadet, vaid panna kokku nimekiri heade praktikate näidetest ning püüda neid praktikaid kohalikes oludes kirjeldada):

* https://github.com/okestonia/esindus/issues/41

Soovitused visandatud kriteeriumide täiendamiseks on igati teretulnud, aga ehk saab siit ka ideid, kuidas ja mida oma avaandmete kataloogi kirjelduses ära märkida. Jõudu kõigile uute toredate andmehulkade avaldamisel!

**Comment by Riigikontroll** [comment]
Riigikontroll on kättesaadavaks teinud PDF-formaadis auditiaruanded alates 1990. aastast, mis on avaldatud Riigikontrolli kodulehel ja mida on võimalik alla laadida. Auditiaruanded sisaldavad mh nii tabeleid kui ka jooniseid. Auditites kasutatavate ilma juurdepääsupiiranguta alusandmete regulaarne avalikustamine on plaanis uue kodulehe arenduste käigus. Auditimaterjalide osas otsustatakse juurdepääs juhtumipõhiselt, s.t päringu korral hinnatakse igakordselt, kas andmete avalikustamine võib kahjustada riigi, auditeeritavate või kolmandate isikute huve.

**Comment by infokujur** [comment]
Töögrupi kohtumise 07.05.2018 kokkuvõte: https://docs.google.com/document/d/16IUX4jSvw_5-pzKqcFKOD1XBT4ApT4JodO7PffRxVfY/edit?usp=drivesdk&ouid=112692841335070909204

Võib dokumenti kommenteerida, aga parem leidke/tehke iga teema jaoks eraldi issue.

**Comment by marmoluik** [comment]
Planeerime 12 kuu jooksul avaldada Swagger UI platvormil Riigikogu veebi teenuste (dokumendid, hääletused, istungitest osavõtt jne) API, kust on võimalik teha erinevate teenuste osas päringuid andmete kätte saamiseks. See hakkab asendama praegust API-t, mis asub aadressil [](https://aavik.riigikogu.ee/api/ems/v1/raml/ems-api-v1.html). Plaanis on ka lisada andmekogude viide opendata.riik.ee keskkonda ja lisada API juurde dokumentatsioon, mis sisaldab infot selle kohta, millega on tegu ja milliseid andmeid on võimalik kätte saada. Isikuandmetega puutub Riigikogu kokku väga vähe. Ainsad teenused, kus kasutame isikuandmeid on Riigikogu kontaktid ja Riigikogule esitatud kollektiivsed pöördumised.

**Comment by andreskytt** [comment]
Super, andke siis teada, kui proovida saab. Samuti tasub seda seltskonda siin testimise ja tagasiside eesmärgil ära kasutada.

**Comment by jtali** [comment]
Maaeluministeeriumil on portaalis hetkel 12 andmekogu. 
Andmekogusid lisandumas ei ole, Kõik mis on olemas on ka opendata.riik.ee lehel olemas.

Nendest Kutselise kalapüügi registri omadele on plaanis lisada xml kujul andmed (hetkel on kättesaadavad ods kujul, läbi kodulehe).

Väetise registrile on ka samuti plaanis xml kujul kättesaadavaks teha (hetkel kättesaadav läbi Põllumajandusameti kodulehe xls kujul).
Veterinaararstide registrile ei tule xml ega muud masinloetavat kuju, kuna sisaldaks antud juhul eeskätt isikuandmeid ja neid ei ole mõstlik kuvada anonümiseeritult.

**Comment by agnekivisaar** [comment]
Haridus-ja Teadusministeerium on avaldanud  järgmised avaandmed:
1. Eesti hariduse infosüsteemi avaandmed; 
2. Eesti teadusinfosüsteemi avaandmed;
3. Eksamite infosüsteemi avaandmed;
4. Haridus- ja Teadusministeeriumi avalik dokumendiregister;
5. Koolide infosüsteemi avaandmed;
6. Kutseregistri avaandmed.

**Comment by infokujur** [comment]
Teeme Groomingul vahekokkuvõtet ja alsutame kasutajate kutsumist selleks, et tekiks rohkem tagasisidet. Palume asutustel endal ka neid kokkuvõtteid levitada, kuna olete ise kõige rohkem teadlikud, kes teile teabepäringuid esitab või muul moel andmeid küsib.

**Comment by atamman** [comment]
Põllumajanduse registrite ja informatsiooni ameti on avaldanud avaandmed  portaalis https://opendata.riik.ee/ ja oma kodulehel http://www.pria.ee/et/pria/avaandmed/

**Comment by infokujur** [comment]
Töögrupi kohtumise 10.10.2018 kokkuvõte: https://docs.google.com/document/d/1uDG5tTyPTSp9W1Q54SpBe7UmCcrhArv8jv37rCZxWek

Võib dokumenti kommenteerida, aga parem leidke/tehke iga teema jaoks eraldi issue.

**Comment by infokujur** [comment]
Praeguseks peaks iga asutus olema viidanud andmehulgad opendata.riik.ee portaalile.
Kui on tekkinud küsimusi, siis konkreetse andmehulga kohta tuleb avada uus issue ning see saab endale asutuse sildi külge.
https://github.com/okestonia/opendata-issue-tracker/labels
Kui silti ei ole, siis palun viidata @infokujur ning see saab loodud.
