### ISSUE TITLE
Visualizing SDG11 - data missing

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#93]
We are creating a sample process - how to get infographics out from open data.
We will learn from difficulties and create new opportunites through collaboration - sharing roles between tech savy and no tech ppl.

**Current state in Estonia**
Last time when SDGs were analysed was **2015**.
Now next time will be **autumn 2018**.

**What Open Data will offer?**
If it will be used, then basicly every time any OD source will be updated, indicator will be also updated and reachable for everybody 24/7.
Basicly it will be real-time **if** we will have enough OD.

**Steps we make:**

Our starting point: http://ec.europa.eu/eurostat/documents/3217494/8461633/KS-04-17-780-EN-N.pdf/f7694981-6190-46fb-99d6-d092ce04083f
Static pdf without underlying data - yep, standard approach to deliver analyses - and not so promising

1) First thing is to understand what data there is - to get the indicator together.
**How?**
- Pinging ppl in Skype, writing emails to get some excel etc
- Hopefully Statistics Estonia will help us.
- If we get something, we will link to this issue.

2) If we will already have some data, we try to build a visual. Using static placeholders and replacing them step by step with OD sources.
- We will post all code here: https://github.com/okestonia/Data-Viz-Protos

It's a loooong process.

Process already started.

**How to contribute?**
1. Search links to data sources. WE NEED DATA!
2. Come to our workshop/get-together April 6th 2018 @Kultuurikatel:
Register here: https://docs.google.com/forms/d/e/1FAIpQLSfv4Aowxr4FoyPzWQ6YDaJLBP9_Hgankq8vArew-IDWq_kIKA/viewform
**What we'll do there?**
Mostly it depends what data we will get ready for visualizing. I'll keep you updated about it.
3. If first scratch is done, then all coding welcome
4. Spread the love - let others know, what is going on

HINT - there are other 16 SDGs also ...

Indicators listed here:
https://riigikantselei.ee/sites/default/files/content-editors/Failid/eesti_saastva_arengu_naitajate_nimekiri_20.12.2017.pdf
- Heas ja rahuldavas seisukorras olevate ehitismälestiste osakaal
- Linnades toimunud liiklusõnnetuste tagajärjel vigastatute ja hukkunute arv
- Peenosakesed PM10 ja PM2,5 välisõhus
- Rohealad linnades
- Rahulolu eluruumide seisundiga
- Ühistranspordiga, jalgrattaga või jalgsi tööl käijate osakaal

Artiklid STG sisu poolest Hea kodanik ajakirjas siin:
https://issuu.com/emsl/docs/hea_kodanik_73

**Comment by infokujur** [comment]
Same work and data is here: https://github.com/okestonia/opendata-issue-tracker/issues/72

**Comment by infokujur** [comment]
Tallinna piirkonna säästva linnaliikuvuse kava 2035
https://www.ttu.ee/public/t/Taiendusoppijale/Avatud_ulikool/lektorid/Mari_Jussi_LiikuvuskavaTutvustus_MJ_2017_08_23_suvekool.pdf

Tallinna lähipiirkonna elanike liikumisviiside uuring (esitluse lõpus loetelu failidest): https://www.mnt.ee/sites/default/files/harjuliikuvusuuringu2017_aruanne2018.pdf

Läänemere linnade säästva liikuvuse uurimisprojekt, kus andmete teema sees (aga tulemusi vist veel väga pole?): http://sumba.eu/en 

Baltic Big & Open Data häkatonilt (2017) Smart Mobility a  tool for the planners to make a better network of roads. The team is looking forward to revolutionizing  Estonian roads infrastructure.

**Comment by infokujur** [comment]
Sustainable development in the European Union
http://ec.europa.eu/eurostat/documents/3217494/8461633/KS-04-17-780-EN-N.pdf/f7694981-6190-46fb-99d6-d092ce04083f

**Comment by infokujur** [comment]
**Updates:**
- Registration here: https://docs.google.com/forms/d/e/1FAIpQLSfv4Aowxr4FoyPzWQ6YDaJLBP9_Hgankq8vArew-IDWq_kIKA/viewform
- I talked @teelmo today - he will join me and @keeganmcbride on it.
- No info from Statistics Estonia yet. Waiting until tomorrow, until starting guerrilla tactics (it's fun, but time-consuming :( ...)

**Comment by infokujur** [comment]
We got this data from Statistics Estonia to start working with:

Näitaja/Aasta | 2004 | 2005 | 2006 | 2007 | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | 2014 | 2015 | 2016
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Ühistranspordiga, jalgrattaga   või jalgsi tööl käijate osatähtsus hõivatute seas, % | 58,1 | 57,4 | 54,4 | 50,4 | 47,2 | 45 | 44,5 | 43,5 | 44 | 43,1 | 42,3 | 43 | 40
..Ühissõidukiga | 29,1 | 30,1 | 27,4 | 26,2 | 24 | 22,7 | 22,3 | 22,3 | 23,1 | 22,9 | 22,6 | 21,9 | 20,9
..Jalgsi | 25,9 | 24,3 | 23,7 | 21,1 | 20 | 19,4 | 19,3 | 18,1 | 18,1 | 17,4 | 16,9 | 17,4 | 16,4
..Jalgrattaga | 3,1 | 3 | 3,3 | 3,1 | 3,2 | 2,9 | 2,9 | 3,1 | 2,8 | 2,8 | 2,8 | 3,2 | 2,9
Peenosakesed PM10 ja PM2,5   välisõhus, tuhat tonni | . | . | . | . | . | . | . | . | . | . | . | . | .
..Peenosakeste PM10 sisaldus välisõhus,   tuhat tonni | 24,9 | 22,5 | 16,3 | 22,8 | 19 | 15,5 | 23,4 | 34,4 | 13 | 17,5 | 13,2 | 14 | ..
..Peenosakeste PM2,5 sisaldus välisõhus,   tuhat tonni | 15,4 | 14,2 | 9,8 | 12,7 | 11,9 | 9,7 | 13,9 | 18,2 | 8,2 | 10,8 | 7,9 | 9,2 | ..

**Comment by infokujur** [comment]
Viz got his special repo: https://github.com/Demokraatialabor/SDG
But open data request will remain here.

**Comment by KristiinaKerge** [comment]
This data http://opendata.letsdoitworld.org is accessible https://opendata.letsdoitworld.org/api/doc/

**Comment by infokujur** [comment]
I'm closing this epic for now.
Please do open also any requests separately or if You have data, then please upload it to opendata.riik.ee
