### ISSUE TITLE
Save the date > Töötuba teemal - Andmekaitse ja avaandmed - Latitude59 raames 25.05.2018

### ISSUE THREAD

**Issue by infokujur** [okestonia/opendata-issue-tracker#97]
Uue andmekaitsemääruse (GDPR) jõustumisel (mai 2018) on mõistlik arutleda määruse nõuete ja võimaluste ning avaandmete temaatika kokkupuutepunktide üle.

Kuna OKEE senistest tegevustest seostub GDPR raamistikuga kõige enam MyData ehk inimkeskse andmekasutuse temaatika, on maikuisel infopäeval plaanis arutleda, kuidas on toimunud ja võiks toimuda määruse nõuete juurutamises inimkesksete lahenduste kasutamine, sh isiklike andmete kasutamine inimese enese poolt.

Avaandmed on isiklike andmete kasutamises kontekstuaalne informatsioon, nende kahe andmetüübi kombineerimisega kaasnevad nii võimalused kui riskid nii avaliku kui erasektori jaoks. Anonümiseeritud isiklikud andmed (nt kodanike poolt sihtotstarbeliselt annetatuna) avavad uusi võimalusi nii ühiskonnakorralduses kui teenusearenduses.

Maikuusse plaanitud infopäeva sisustavad esinejad MyData võrgustikust (Paul-Olivier Dehaye, PersonalData.IO rajaja), Open Knowledge Eesti ja Soome organisatsioonidest, ning Eesti ja Soome avalikust ja ärisektorist.

**Comment by tanelmallo** [comment]
Uue andmekaitsemääruse (GDPR) jõustumisel (mai 2018) on mõistlik arutleda määruse nõuete ja võimaluste ning avaandmete temaatika kokkupuutepunktide üle. Kuna OKEE senistest tegevustest seostub GDPR raamistikuga kõige enam MyData ehk inimkeskse andmekasutuse temaatika, on maikuisel infopäeval plaanis arutleda, kuidas on toimunud ja võiks toimuda määruse nõuete juurutamises inimkesksete lahenduste kasutamine, sh isiklike andmete kasutamine inimese enese poolt. Avaandmed on isiklike andmete kasutamises kontekstuaalne informatsioon, nende kahe andmetüübi kombineerimisega kaasnevad nii võimalused kui riskid nii avaliku kui erasektori jaoks. Anonümiseeritud isiklikud andmed (nt kodanike poolt sihtotstarbeliselt annetatuna) avavad uusi võimalusi nii ühiskonnakorralduses kui teenusearenduses. Maikuusse plaanitud infopäeva sisustavad esinejad MyData võrgustikust (Paul-Olivier Dehaye, PersonalData.IO rajaja), Open Knowledge Eesti ja Soome organisatsioonidest, ning Eesti ja Soome avalikust ja ärisektorist.
