### ISSUE TITLE
Traffic death data

### ISSUE THREAD

**Issue by keeganmcbride** [okestonia/opendata-issue-tracker#98]
I think we can get the data from here for part of the SDG? 

http://pxweb.tai.ee/PXWeb2015/pxweb/et/02Haigestumus/02Haigestumus__09Vigastused/?rxid=9d045fce-5241-46cc-a6b7-b96e77182f49

https://www.mnt.ee/et/ametist/statistika/liiklusonnetuste-statistika

**Comment by Kristjan4** [comment]
Estonian Road Administration has published traffic death data : https://opendata.riik.ee/andmehulgad/maanteeamet-malis/

**Comment by andreskytt** [comment]
Closing, should be OK.
